-- Sourced identity catalogue. Inclusion does not publish a clinical review or self-treatment protocol.
CREATE TABLE IF NOT EXISTS ilb_ehr_catalogue (
 practice_code VARCHAR(64) PRIMARY KEY,
 category_name VARCHAR(120) NOT NULL,
 record_kind ENUM('MODALITY','BRANCH','FAMILY','DELIVERY_STYLE') NOT NULL,
 scope_status ENUM('CORE','RELATED') NOT NULL,
 parent_practice_code VARCHAR(64) NULL,
 aliases_text TEXT NOT NULL,
 overview_text TEXT NOT NULL,
 source_url TEXT NOT NULL,
 source_name VARCHAR(255) NOT NULL,
 source_checked_on DATE NOT NULL,
 publication_status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
 FOREIGN KEY(practice_code) REFERENCES ilb_ehr_practice(practice_code),
 FOREIGN KEY(parent_practice_code) REFERENCES ilb_ehr_practice(practice_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
START TRANSACTION;
INSERT INTO ilb_ehr_practice(practice_code,department_code,practice_name) VALUES
('PRANIC_HEALING','ENERGY_HEALING','Pranic Healing'),
('MAGNIFIED_HEALING','ENERGY_HEALING','Magnified Healing'),
('REIKI','ENERGY_HEALING','Reiki'),
('THERAPEUTIC_TOUCH','ENERGY_HEALING','Therapeutic Touch'),
('HEALING_TOUCH','ENERGY_HEALING','Healing Touch'),
('QUANTUM_TOUCH','ENERGY_HEALING','Quantum-Touch'),
('ACCESS_BARS','ENERGY_HEALING','Access Bars'),
('DISTANCE_HEALING','ENERGY_HEALING','Distance healing'),
('CHAKRA_AURA','ENERGY_HEALING','Chakra and aura practices'),
('CRYSTAL_ENERGY','ENERGY_HEALING','Crystal-based energy healing'),
('RECONNECTIVE_HEALING','ENERGY_HEALING','Reconnective Healing'),
('THE_RECONNECTION','ENERGY_HEALING','The Reconnection'),
('THETAHEALING','ENERGY_HEALING','ThetaHealing'),
('EDEN_ENERGY_MEDICINE','ENERGY_HEALING','Eden Energy Medicine'),
('BENGSTON_METHOD','ENERGY_HEALING','Bengston Energy Healing Method'),
('BRENNAN_HEALING','ENERGY_HEALING','Brennan Healing Science'),
('POLARITY_THERAPY','ENERGY_HEALING','Polarity Therapy'),
('JIN_SHIN_JYUTSU','ENERGY_HEALING','Jin Shin Jyutsu'),
('JOHREI','ENERGY_HEALING','Johrei'),
('MAHIKARI','ENERGY_HEALING','Sukyo Mahikari spiritual purification'),
('VORTEX_HEALING','ENERGY_HEALING','VortexHealing'),
('INTEGRATED_ENERGY_THERAPY','ENERGY_HEALING','Integrated Energy Therapy'),
('RAHANNI','ENERGY_HEALING','Rahanni Celestial Healing'),
('BIOFIELD_TUNING','ENERGY_HEALING','Biofield Tuning'),
('BIOGEOMETRY','ENERGY_HEALING','BioGeometry'),
('HEARTFULNESS','ENERGY_HEALING','Heartfulness and Spiritual Anatomy'),
('SAT_NAM_RASAYAN','ENERGY_HEALING','Sat Nam Rasayan'),
('HOOPONOPONO','ENERGY_HEALING','Self I-Dentity through Hooponopono'),
('SOUND_HEALING','ENERGY_HEALING','Sound healing'),
('AGNIHOTRA','ENERGY_HEALING','Agnihotra and Homa Therapy'),
('KARUNA_REIKI','ENERGY_HEALING','Karuna Reiki'),
('HOLY_FIRE_REIKI','ENERGY_HEALING','Holy Fire Reiki'),
('SEICHIM','ENERGY_HEALING','Seichim and Seichem'),
('SEKHEM_BELOT','ENERGY_HEALING','Sekhem (Helen Belot lineage)'),
('EXTERNAL_QIGONG','ENERGY_HEALING','External qi healing'),
('PSYCH_K','ENERGY_HEALING','PSYCH-K'),
('EMOTION_CODE','ENERGY_HEALING','The Emotion Code'),
('BODY_CODE','ENERGY_HEALING','The Body Code'),
('JIKIDEN_REIKI','ENERGY_HEALING','Jikiden Reiki'),
('GENDAI_REIKI','ENERGY_HEALING','Gendai Reiki'),
('TERA_MAI','ENERGY_HEALING','Tera-Mai Reiki'),
('ANGELIC_REIKI','ENERGY_HEALING','Angelic Reiki'),
('DOMANCIC_METHOD','ENERGY_HEALING','Domancic bioenergy method'),
('SAHAJA_YOGA','ENERGY_HEALING','Sahaja Yoga subtle-system practice'),
('MANTRA_PRACTICES','ENERGY_HEALING','Mantra and chanting practices')
ON DUPLICATE KEY UPDATE practice_name=VALUES(practice_name);
INSERT INTO ilb_ehr_catalogue VALUES
('PRANIC_HEALING','Biofield and proximity','MODALITY','CORE',NULL,'Pranic healing; MCKS Pranic Healing','No-touch practice described through prana and an energy body.','https://worldpranichealing.com/about/pranichealing','World Pranic Healing','2026-09-30','PUBLISHED'),
('MAGNIFIED_HEALING','Biofield and spiritual','MODALITY','CORE',NULL,'Magnified Healing Phase I','Spiritual practice combining movement, breath and affirmations.','https://magnifiedhealing.com/phase-1/','Magnified Healing','2026-09-30','PUBLISHED'),
('REIKI','Biofield and proximity','MODALITY','CORE',NULL,'Usui Reiki; Reiki Ryoho','Japanese-origin practice using hands on or near the body.','https://www.nccih.nih.gov/health/reiki','NCCIH','2026-09-30','PUBLISHED'),
('THERAPEUTIC_TOUCH','Biofield and proximity','MODALITY','CORE',NULL,'TT','Structured practice described as working with a human energy field.','https://therapeutictouch.org/','Therapeutic Touch International Association','2026-09-30','PUBLISHED'),
('HEALING_TOUCH','Biofield and proximity','MODALITY','CORE',NULL,'HT','Energy-based practice using intentional touch and hand movements.','https://www.healingtouchprogram.com/what-is-healing-touch','Healing Touch Program','2026-09-30','PUBLISHED'),
('QUANTUM_TOUCH','Biofield and proximity','MODALITY','CORE',NULL,'Quantum Touch','Method using breathwork, body awareness and focused intention.','https://quantumtouch.com/','Quantum-Touch','2026-09-30','PUBLISHED'),
('ACCESS_BARS','Biofield and touch','MODALITY','CORE',NULL,'Bars; Access Bars','Branded method using light touch on points of the head.','https://www.accessconsciousness.com/bars/','Access Consciousness','2026-09-30','PUBLISHED'),
('DISTANCE_HEALING','Remote practice','DELIVERY_STYLE','CORE',NULL,'Distant healing; remote healing; absent healing','Remote delivery used by multiple traditions; not a single independent modality.','https://www.reconnectivehealing.com/pages/faqs','Reconnective Healing FAQ','2026-09-30','PUBLISHED'),
('CHAKRA_AURA','Subtle-body practices','FAMILY','CORE',NULL,'Chakra balancing; aura work','Umbrella for practices using chakra and aura frameworks; lineage-specific methods require separate extraction.','https://www.daaji.org/spiritual-anatomy-book','Daaji Spiritual Anatomy','2026-09-30','PUBLISHED'),
('CRYSTAL_ENERGY','Objects and subtle-body practices','FAMILY','CORE',NULL,'Crystal healing; Pranic Crystal Healing','Umbrella for crystal-based energy methods; catalogue identity does not establish effects.','https://register.worldpranichealing.com/courses/batch/47506/uadnch','World Pranic Healing training prerequisites','2026-09-30','PUBLISHED'),
('RECONNECTIVE_HEALING','Biofield and spiritual','MODALITY','CORE',NULL,'Reconnective Healing','Branded approach described through energy, light and information.','https://www.reconnectivehealing.com/pages/what-is-reconnective-healing','Reconnective Healing','2026-09-30','PUBLISHED'),
('THE_RECONNECTION','Biofield and spiritual','BRANCH','CORE','RECONNECTIVE_HEALING','The Reconnection','Related application distinguished by its organisation from Reconnective Healing.','https://www.reconnectivehealing.com/pages/reconnective-healing-the-reconnection/','Reconnective Healing organisation','2026-09-30','PUBLISHED'),
('THETAHEALING','Belief and spiritual practices','MODALITY','CORE',NULL,'Theta Healing','Spiritual method described through meditation and belief change.','https://help.thetahealing.com/en/articles/6350402-what-is-thetahealing','ThetaHealing Help Center','2026-09-30','PUBLISHED'),
('EDEN_ENERGY_MEDICINE','Subtle-body practices','MODALITY','CORE',NULL,'Eden Method','Donna Eden approach described around multiple energy systems.','https://edenenergymedicine.com/principles-of-energy-medicine/','Eden Energy Medicine','2026-09-30','PUBLISHED'),
('BENGSTON_METHOD','Biofield and intention','MODALITY','CORE',NULL,'Bengston Method; image cycling','Named energy-healing method associated with image cycling.','https://bengstonresearch.com/healing-method','Bengston Research','2026-09-30','PUBLISHED'),
('BRENNAN_HEALING','Biofield and proximity','MODALITY','CORE',NULL,'BHS; Hands of Light approach','Barbara Brennan approach using a human energy-consciousness framework.','https://barbarabrennan.com/about-barbara-brennan/','Barbara Brennan School of Healing','2026-09-30','PUBLISHED'),
('POLARITY_THERAPY','Energy and bodywork','MODALITY','RELATED',NULL,'Polarity','System combining touch, exercise, nutrition and self-awareness; includes physical bodywork.','https://polaritytherapy.org/','American Polarity Therapy Association','2026-09-30','PUBLISHED'),
('JIN_SHIN_JYUTSU','Energy and touch','MODALITY','RELATED',NULL,'JSJ','Japanese energy art involving gentle hand placement; related touch-based practice.','https://www.jinshinjyutsu.de/en/','Jin Shin Jyutsu European Office','2026-09-30','PUBLISHED'),
('JOHREI','Spiritual transmission','MODALITY','CORE',NULL,'Jyorei','Japanese-origin spiritual practice described as non-invasive energy healing.','https://www.johrei.org/johrei','Johrei Fellowship','2026-09-30','PUBLISHED'),
('MAHIKARI','Spiritual transmission','MODALITY','RELATED',NULL,'Mahikari; True Light','Religious spiritual-purification practice; organisation distinguishes it from healing treatment.','https://sukyomahikari.org.au/ourvision/artspiritualpurification/','Sukyo Mahikari Australia','2026-09-30','PUBLISHED'),
('VORTEX_HEALING','Biofield and spiritual','MODALITY','CORE',NULL,'Vortex Healing','Branded spiritual system described as multidimensional healing and awakening.','https://vortexhealing.org/','VortexHealing','2026-09-30','PUBLISHED'),
('INTEGRATED_ENERGY_THERAPY','Biofield and spiritual','MODALITY','CORE',NULL,'IET','Named method described through angelic energy and integration points.','https://www.learniet.com/about-iet-classes/','Learn IET','2026-09-30','PUBLISHED'),
('RAHANNI','Biofield and spiritual','MODALITY','CORE',NULL,'Rahanni','Named spiritual energy-healing system associated with Carol Stacey.','https://www.rahannicelestialhealing.co.uk/discover-rahanni','Rahanni Celestial Healing Hub','2026-09-30','PUBLISHED'),
('BIOFIELD_TUNING','Sound and vibration','MODALITY','CORE',NULL,'Biofield Tuning','Named sound-based method using tuning forks and a biofield framework.','https://www.biofieldtuning.com/what-is-biofield-tuning','Biofield Tuning','2026-09-30','PUBLISHED'),
('BIOGEOMETRY','Geometry and environmental energy','MODALITY','RELATED',NULL,'BioGeometry energy balancing','Branded geometry-based energy-balancing approach; environmental applications require separate review.','https://www.biogeometry.ca/','BioGeometry','2026-09-30','PUBLISHED'),
('HEARTFULNESS','Meditation and subtle-body practices','MODALITY','RELATED',NULL,'Sahaj Marg; Spiritual Anatomy','Meditation tradition with a spiritual-anatomy framework; a book and foundation are not separate modalities.','https://www.daaji.org/spiritual-anatomy-book','Daaji','2026-09-30','PUBLISHED'),
('SAT_NAM_RASAYAN','Meditative healing','MODALITY','CORE',NULL,'Satnam Rasayan','Named contemplative healing practice taught through an international school.','https://www.satnamrasayan.it/about-sat-nam-rasayan/','Sat Nam Rasayan International School','2026-09-30','PUBLISHED'),
('HOOPONOPONO','Reconciliation and spiritual practices','MODALITY','RELATED',NULL,'Ho''oponopono; SITH','Modern spiritual self-practice; distinguish it from traditional Hawaiian communal reconciliation.','https://hooponopono-asia.org/en/about-introduction/','Hooponopono official regional organisation','2026-09-30','PUBLISHED'),
('SOUND_HEALING','Sound and vibration','FAMILY','RELATED',NULL,'Sound baths; singing bowls; gong baths; vocal toning','Umbrella for sound-based practices; sound waves and subtle-energy claims require separate evidence.','https://www.soundhealingindia.com/','Sound Healing India practitioner description','2026-09-30','PUBLISHED'),
('AGNIHOTRA','Ritual and environmental practices','FAMILY','RELATED',NULL,'Homa Therapy; Agnihotra','Fire and mantra ritual described in Homa Therapy; not a biofield hand technique.','https://www.agnihotra.org/2015/03/29/how-to-perform-agnihota-instructions/','Agnihotra organisation','2026-09-30','PUBLISHED'),
('KARUNA_REIKI','Reiki branches','BRANCH','CORE','REIKI','Karuna','Named Reiki branch; retain its lineage separately from the Reiki umbrella.','https://www.reiki.org/karuna-reiki','International Center for Reiki Training','2026-09-30','PUBLISHED'),
('HOLY_FIRE_REIKI','Reiki branches','BRANCH','CORE','REIKI','Holy Fire III Reiki','Named Reiki approach included in the organisation''s Usui and Karuna training.','https://www.reiki.org/what-holy-fire-reiki','International Center for Reiki Training','2026-09-30','PUBLISHED'),
('SEICHIM','Biofield and spiritual','MODALITY','CORE',NULL,'Seichem; Seichim','Energy-healing system described through elemental rays; spelling alone does not resolve all lineages.','https://www.reikicouncil.org.uk/seichem/','Reiki Council','2026-09-30','PUBLISHED'),
('SEKHEM_BELOT','Biofield and spiritual','MODALITY','CORE',NULL,'Sekhem','Named Sekhem lineage whose own source distinguishes it from Reiki and Seichim.','https://www.sekhem.com.au/about-sekhem','Sekhem organisation','2026-09-30','PUBLISHED'),
('EXTERNAL_QIGONG','Qi practices','FAMILY','CORE',NULL,'External qigong; emitted qi','Qi transmission practices; keep separate from internal movement-based self-cultivation.','https://qigonginstitute.org/category/16/frequently-asked-questions-faq','Qigong Institute','2026-09-30','PUBLISHED'),
('PSYCH_K','Belief and spiritual practices','MODALITY','RELATED',NULL,'Psych K','Branded belief-change process; retained as a related spiritual approach.','https://www.psych-k.com/what-is-psych-k/','PSYCH-K Centre International','2026-09-30','PUBLISHED'),
('EMOTION_CODE','Emotion and energy practices','MODALITY','CORE',NULL,'Emotion Code','Named method treated as part of the broader Body Code system by its organisation.','https://discoverhealing.com/faq-items/what-is-the-difference-between-the-emotion-code-and-the-body-code/','Discover Healing','2026-09-30','PUBLISHED'),
('BODY_CODE','Emotion and energy practices','MODALITY','CORE',NULL,'Body Code','Named system incorporating the Emotion Code; distinct catalogue identity.','https://discoverhealing.com/faq-items/what-is-the-difference-between-the-emotion-code-and-the-body-code/','Discover Healing','2026-09-30','PUBLISHED'),
('JIKIDEN_REIKI','Reiki branches','BRANCH','CORE','REIKI','Jikiden','Japanese Reiki lineage documented by its official institute.','https://jikiden-reiki.com/en/','Jikiden Reiki Kenkyukai','2026-09-30','PUBLISHED'),
('GENDAI_REIKI','Reiki branches','BRANCH','CORE','REIKI','Gendai Reiki Ho','Named Reiki approach described by the Gendai Reiki Network.','https://www.gendaireiki.or.jp/reiki?lang=en','Gendai Reiki Network','2026-09-30','PUBLISHED'),
('TERA_MAI','Reiki branches','BRANCH','CORE','REIKI','Tera Mai','Named Reiki branch listed in the Reiki Council style directory.','https://www.reikicouncil.org.uk/reiki-styles/','Reiki Council','2026-09-30','PUBLISHED'),
('ANGELIC_REIKI','Biofield and spiritual','MODALITY','CORE',NULL,'Angelic Reiki','Spiritual energy-healing method documented by Angelic Reiki International.','https://angelicreikiinternational.com/about-angelic-reiki/','Angelic Reiki International','2026-09-30','PUBLISHED'),
('DOMANCIC_METHOD','Biofield and proximity','MODALITY','CORE',NULL,'Domancic Method; biotherapy','Named bioenergy method documented by Zdenko Domancic''s organisation.','https://www.zdenkodomancic.com/en/about-the-method.aspx','Zdenko Domancic official site','2026-09-30','PUBLISHED'),
('SAHAJA_YOGA','Meditation and subtle-body practices','MODALITY','RELATED',NULL,'Sahaja meditation','Meditative tradition describing kundalini and a subtle system.','https://shrimatajifoundation.org/sahaja-yoga/','Shri Mataji Foundation','2026-09-30','PUBLISHED'),
('MANTRA_PRACTICES','Sound and vibration','FAMILY','RELATED',NULL,'Chanting; mantra meditation','Lineage-specific spoken or sung practices; retain spiritual meaning and acoustic effects separately.','https://us.sahajayoga.org/faq/','Sahaja Yoga US','2026-09-30','PUBLISHED')
ON DUPLICATE KEY UPDATE category_name=VALUES(category_name),record_kind=VALUES(record_kind),scope_status=VALUES(scope_status),parent_practice_code=VALUES(parent_practice_code),aliases_text=VALUES(aliases_text),overview_text=VALUES(overview_text),source_url=VALUES(source_url),source_name=VALUES(source_name),source_checked_on=VALUES(source_checked_on);
INSERT INTO ilb_ehr_practice(practice_code,department_code,practice_name) VALUES
('CORE_SHAMANISM','ENERGY_HEALING','Core Shamanism healing practices'),
('SPIRITUALIST_HEALING','ENERGY_HEALING','Spiritualist healing'),
('CHRISTIAN_SCIENCE_HEALING','ENERGY_HEALING','Christian Science prayer healing'),
('RADIONICS','ENERGY_HEALING','Radionics'),
('HEALING_DOWSING','ENERGY_HEALING','Healing dowsing and radiesthesia')
ON DUPLICATE KEY UPDATE practice_name=VALUES(practice_name);
INSERT INTO ilb_ehr_catalogue VALUES
('CORE_SHAMANISM','Spirit and ritual practices','FAMILY','RELATED',NULL,'Extraction healing; power soul retrieval; power animal retrieval','Modern Foundation for Shamanic Studies teaching framework; does not represent all Indigenous healing traditions.','https://www.shamanism.org/workshops/core-shamanism-healing-practice/','Foundation for Shamanic Studies','2026-09-30','PUBLISHED'),
('SPIRITUALIST_HEALING','Spiritual transmission','FAMILY','CORE',NULL,'Healing mediumship; spiritual healing','Spiritualist healing framework describing channelled spiritual forces, hands, prayer and directed thought.','https://www.mdcsnu.org/healing','Manchester District Council of the Spiritualists National Union','2026-09-30','PUBLISHED'),
('CHRISTIAN_SCIENCE_HEALING','Prayer and religious practices','MODALITY','RELATED',NULL,'Christian Science treatment','Specific religious prayer-healing tradition; not an umbrella for all Christian healing practices.','https://www.christianscience.com/what-we-believe/healing-in-christian-science','Christian Science organisation','2026-09-30','PUBLISHED'),
('RADIONICS','Instrument and intention practices','MODALITY','CORE',NULL,'Radionic healing','Practice described through distant energy work and radionic instruments; distinct from validated electromagnetic medical treatments.','https://www.radionic.co.uk/what-is-radionics/','Radionic Association','2026-09-30','PUBLISHED'),
('HEALING_DOWSING','Instrument and intention practices','FAMILY','RELATED',NULL,'Pendulum healing; radiesthesia; environmental energy clearing','Dowsing-based assessment and spiritual energy work; distinguish personal and environmental applications.','https://britishdowsing.net/healing-sick-houses-from-a-spiritual-healing-perspective/','Roy and Ann Procter original article archive','2026-09-30','PUBLISHED')
ON DUPLICATE KEY UPDATE overview_text=VALUES(overview_text),source_url=VALUES(source_url),source_name=VALUES(source_name),source_checked_on=VALUES(source_checked_on);
COMMIT;
