-- Focused Magnified Healing entry; apply after department, LOINC and Pranic migrations.
START TRANSACTION;
INSERT INTO ilb_ehr_source(source_key,title,source_type,source_url,citation_text,correction_check,checked_at,publication_status) VALUES
('MH_ORIGINS','Magnified Healing organisation history','TEACHING','https://magnifiedhealing.com/about-magnified-healing/','Magnified Healing official website. Opening history and four-level outline','Teaching webpage; not a clinical study','2026-09-30','PUBLISHED'),
('MH_FOUNDERS','Magnified Healing co-founders','TEACHING','https://magnifiedhealing.com/about-us/','Magnified Healing official website. Biographies of Kathryn Anderson and Gisele King','Teaching webpage; not a clinical study','2026-09-30','PUBLISHED'),
('MH_PHASE1','First Phase workshop','TEACHING','https://magnifiedhealing.com/phase-1/','Magnified Healing official website. Learning and practice overview','Teaching webpage; not a clinical study','2026-09-30','PUBLISHED'),
('MH_PHASE3','Light Healing practitioner workshop','TEACHING','https://magnifiedhealing.com/phase-3/','Magnified Healing official website. Spiritual light, distance and DNA/RNA claims','Teaching webpage; not a clinical study','2026-09-30','PUBLISHED')
ON DUPLICATE KEY UPDATE title=VALUES(title),source_url=VALUES(source_url),citation_text=VALUES(citation_text),checked_at=VALUES(checked_at);
INSERT INTO ilb_ehr_section(practice_code,section_key,position_no,title,body_text,source_key,publication_status) VALUES
('MAGNIFIED_HEALING','overview',1,'What is Magnified Healing?','Magnified Healing is a spiritual healing system associated with Kathryn Anderson and Gisele King. It describes collaboration with divine energy and Kwan Yin. These descriptions document the tradition; they are not measured physical mechanisms.','MH_FOUNDERS','PUBLISHED'),
('MAGNIFIED_HEALING','origins',2,'How was it developed?','The organisation dates an initial introduction to 1983 and an expanded form to 1992, attributing this to Kwan Yin. This is its spiritual origin account. No independent experimental development record was identified in this focused review.','MH_ORIGINS','PUBLISHED'),
('MAGNIFIED_HEALING','practice',3,'What happens in practice?','The public first-phase outline combines breathing, affirmations and sacred geometry with self-healing, work with others and initiation. Four training levels are described. Workshop certification records training within the system; it is not clinical validation. Detailed manual procedures have not been reproduced here.','MH_PHASE1','PUBLISHED'),
('MAGNIFIED_HEALING','findings',4,'What has research found?','The focused searches on 30 September 2026 did not identify an eligible controlled clinical study specifically testing this named modality. Search-engine queries targeting PubMed, Europe PMC, ClinicalTrials.gov and WHO ICTRP returned no relevant records; direct database queries were inaccessible. This is a limited search result, not proof that no study exists. No clinical effect estimate can be supplied.',NULL,'PUBLISHED'),
('MAGNIFIED_HEALING','claims',5,'Which claims need testing?','The advanced workshop describes spiritual light, distant sessions and DNA/RNA recoding. The reviewed material supplied no controlled molecular or physical measurements demonstrating these claims. Its laser terminology must not be equated with a measured optical beam or medical laser treatment.','MH_PHASE3','PUBLISHED'),
('MAGNIFIED_HEALING','measurements',6,'How do measurements connect?','Record phase, manual edition, delivery mode, session duration and concurrent practices. Link recipient observations through existing approved LOINC identities, preserving specimen, method, date, original value and unit. Sacred geometry, initiation and practitioner perceptions use local research variables; no LOINC code is invented. Compare human and veterinary outcomes separately.',NULL,'PUBLISHED'),
('MAGNIFIED_HEALING','verification',7,'How can we verify outcomes?','Three draft designs separate recipient wellbeing, distant-session effects and a proposed physical signal. Prespecify one primary endpoint, randomisation, masking, sample size and analysis. No experiments have been registered or conducted. The designs require appropriate investigator and ethics review before enrolment.',NULL,'PUBLISHED'),
('MAGNIFIED_HEALING','library',8,'Sources and learning materials','Sources are linked and paraphrased. Official manuals remain rights-restricted; this entry does not host them or confer practitioner certification. Teachings, experiences and clinical or molecular findings retain separate labels. Research on Reiki or Pranic Healing cannot automatically validate Magnified Healing.',NULL,'PUBLISHED')
ON DUPLICATE KEY UPDATE title=VALUES(title),body_text=VALUES(body_text),source_key=VALUES(source_key),position_no=VALUES(position_no);
INSERT INTO ilb_ehr_claim(claim_key,practice_code,claim_text,claim_kind,evidence_status,conclusion_text,reviewed_by,reviewed_at,publication_status) VALUES
('MH_SPIRITUAL','MAGNIFIED_HEALING','The system teaches a spiritual origin involving Kwan Yin.','TEACHING','SUPPORTED','Supported as an organisation teaching, not as independently established causation.','ILMB focused source review','2026-09-30','PUBLISHED'),
('MH_WELLBEING','MAGNIFIED_HEALING','Magnified Healing improves recipient wellbeing.','OUTCOME','INSUFFICIENT','No eligible controlled study was identified in the limited searches; benefit magnitude and uncertainty remain unestimated.','ILMB focused source review','2026-09-30','PUBLISHED'),
('MH_DISTANCE','MAGNIFIED_HEALING','Sessions affect recipients at a distance.','OUTCOME','INSUFFICIENT','A blinded randomised distance-session experiment is needed; the teaching page does not establish an outcome effect.','ILMB focused source review','2026-09-30','PUBLISHED'),
('MH_DNA','MAGNIFIED_HEALING','The practice recodes or activates DNA/RNA.','MECHANISM','INSUFFICIENT','The reviewed source provides a claim without controlled molecular measurements. Spiritual terminology does not identify a molecular endpoint.','ILMB focused source review','2026-09-30','PUBLISHED'),
('MH_LIGHT','MAGNIFIED_HEALING','Spiritual light corresponds to a physical laser signal.','MECHANISM','INSUFFICIENT','The teaching uses laser language; no calibrated optical signal evidence was identified in the selected sources.','ILMB focused source review','2026-09-30','PUBLISHED')
ON DUPLICATE KEY UPDATE claim_text=VALUES(claim_text),conclusion_text=VALUES(conclusion_text),evidence_status=VALUES(evidence_status);
INSERT INTO ilb_ehr_protocol(protocol_code,practice_code,question_text,primary_endpoint,design_text,analysis_plan,research_status,publication_status) VALUES
('MH_O01','MAGNIFIED_HEALING','Does first-phase practice change a defined wellbeing outcome?','Between-group difference in one prespecified validated wellbeing scale at four weeks.','Randomised matched-attention comparator; freeze phase, edition, dose and usual care. Mask assessors and analysts; record expectations, adherence, adverse events and concurrent care. Ethics and consent required before enrolment.','Baseline-adjusted intention-to-treat analysis with confidence interval; prespecify missing data and multiplicity. Calculate power from independent variance and a meaningful difference.','DRAFT','DRAFT'),
('MH_D01','MAGNIFIED_HEALING','Does a concealed distant-session assignment affect a defined recipient outcome?','Between-group difference in one prespecified recipient outcome at a fixed assessment time.','Randomise recipients to scheduled active or sham distance sessions. Recipients and assessors do not know assignment or timing; no practitioner contact during the study. Conceal allocation, log exact session times and protocol deviations.','Preregister primary comparison, missing-data handling and sample-size calculation. Repeated measures must account for recipient clustering. Independent replication required.','DRAFT','DRAFT'),
('MH_M01','MAGNIFIED_HEALING','Is a predicted physical signal detected during a session?','One prespecified calibrated quantity in a fixed location and time window.','Choose an explicit quantitative prediction before selecting an instrument. Randomise active and sham periods; blind operator and analyst. Include matched movement, empty-room and drift controls. Spiritual laser terminology does not specify an optical wavelength.','Prespecify threshold, bandwidth, false-positive rate and artefact checks; preserve raw data and calibration. A signal does not alone establish recipient benefit or DNA change.','DRAFT','DRAFT')
ON DUPLICATE KEY UPDATE question_text=VALUES(question_text),primary_endpoint=VALUES(primary_endpoint),design_text=VALUES(design_text),analysis_plan=VALUES(analysis_plan);
UPDATE ilb_ehr_practice SET description_text='Spiritual healing system; focused initial source review with explicit evidence gaps.',review_status='IN_REVIEW',publication_status='PUBLISHED' WHERE practice_code='MAGNIFIED_HEALING';
COMMIT;
