-- ILoveMyBody Phase 106 split seed
-- Extracted verbatim from canonical Phase 106 migration artifact.

INSERT INTO ilb_psoriasis_modality_reference(modality_id,modality_name,domain_name,role_type,mechanistic_rationale,evidence_position,governance_rule,eligibility_note,source_url) VALUES
('MOD-ND-001','Emollient/barrier care','Skin/barrier','Direct supportive','Reduces dryness/scale/fissuring and supports barrier comfort','Established supportive care','Does not directly extinguish IL-23/IL-17 disease driver','Eligible broadly','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-002','Narrowband UVB','Phototherapy','Direct skin/immune','UVB alters cutaneous immune activity and epidermal proliferation','Evidence-based treatment','Dose/burn/phototoxicity governance required','Clinician-directed','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-003','Weight management when overweight/obese','Metabolic','Indirect disease modifier','Reduces adiposity/metabolic inflammatory burden and improves overall health','Supported; interventional evidence for benefit in some psoriasis outcomes','Not relevant as a weight-loss prescription without clinical context','Assess metabolic pathway','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-004','Smoking cessation','Exposure','Risk modifier','Removes tobacco exposure; particularly relevant to palmoplantar pustulosis association','Strong health benefit; psoriasis association evidence','Not a standalone psoriasis cure','Assess smoking exposure','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-005','Alcohol moderation','Exposure','Risk modifier','Reduces alcohol-related aggravation and systemic treatment interactions','Supported general/observational','Not a standalone psoriasis cure','Assess intake','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-006','Sleep optimization','Neuro/metabolic','Indirect modifier','Targets sleep disruption and recovery','General health benefit; psoriasis-specific causal effect uncertain','Measure sleep and skin separately','Assess sleep pathway','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-007','Structured stress management / CBT','Psychological','Indirect modifier','Reduces distress and maladaptive stress responses','Evidence for psychological benefit; psoriasis effects variable','Do not infer cytokine normalization without measurement','Assess stress pathway','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-EMDR','EMDR','Trauma/neuropsychological','Upstream modifier','Targets distressing memory/threat processing; may reduce autonomic arousal','Established for PTSD; psoriasis-specific efficacy unproven','Not an IL-17 blocker; not a psoriasis cure','Only when clinically appropriate trauma target exists','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-009','Mindfulness/relaxation','Psychological','Indirect modifier','May reduce perceived stress and improve coping','Variable/adjunctive evidence','Skin outcomes must be measured separately','Optional','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-010','Exercise','Metabolic/cardiovascular','Whole-body health','Improves cardiometabolic fitness and mental health','Strong general health evidence; psoriasis skin effect variable','Adapt to joints and disease severity','Assess comorbidity/function','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-011','Nutrition pattern / diet quality','Nutrition','Indirect modifier','Supports cardiometabolic health; calorie balance relevant to weight when appropriate','No single diet proven to cure psoriasis','Avoid unvalidated elimination diets as default','Personalize to nutritional needs/comorbidities','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('MOD-ND-012','Acupuncture','Complementary','Symptom/modifier hypothesis','May affect pain/stress pathways; psoriasis evidence limited','Insufficient for disease-modifying claim','Do not encode as psoriasis cure or IL-17 substitute','Research/adjunct only','https://www.aad.org/member/clinical-quality/guidelines/psoriasis')
ON DUPLICATE KEY UPDATE modality_name=VALUES(modality_name),mechanistic_rationale=VALUES(mechanistic_rationale),evidence_position=VALUES(evidence_position),governance_rule=VALUES(governance_rule),eligibility_note=VALUES(eligibility_note),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_red_flag(red_flag_id,signal_text,concern_text,example_features,action_text,ilmb_rule,source_url) VALUES
('RF-001','Generalized pustules + systemic illness','Possible GPP flare','Fever/chills, rapid pulse, weakness, widespread painful pustules','URGENT medical assessment','Do not route into routine self-help pathway','https://www.psoriasis.org/generalized-pustular-psoriasis/'),
('RF-002','>80–90% BSA erythema/exfoliation','Possible erythrodermic psoriasis','Widespread red/dark inflamed skin, shedding, temperature instability, edema, tachycardia','URGENT medical assessment','Fluid/temperature/cardiovascular complications possible','https://www.psoriasis.org/erythrodermic-psoriasis/'),
('RF-003','Rapid deterioration after systemic steroid withdrawal','Severe rebound/pustular/erythrodermic risk','Recent systemic corticosteroid cessation + worsening','URGENT clinician review','Medication-change safety signal','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('RF-004','Signs of serious infection','Infection/sepsis differential','High fever, hypotension, confusion, rapidly worsening painful skin','URGENT/emergency evaluation','Do not assume pustules are sterile when patient is systemically unwell','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('RF-005','New swollen joints/dactylitis/major morning stiffness','Possible PsA','Joint swelling, heel pain, sausage digit, persistent stiffness','Prompt rheumatology/medical assessment','Early treatment can reduce permanent damage','https://www.psoriasis.org/psoriatic-arthritis-screening-test/'),
('RF-006','Eye pain/redness/photophobia/vision change','Possible uveitis or ocular emergency','Acute inflammatory eye symptoms','URGENT ophthalmic assessment','Especially relevant in psoriatic disease context','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('RF-007','Suicidal thoughts / severe mental-health crisis','Mental-health emergency','Self-harm thoughts, inability to stay safe','Emergency mental-health support','Separate from psoriasis causality; safety first','https://pubmed.ncbi.nlm.nih.gov/33812489/')
ON DUPLICATE KEY UPDATE signal_text=VALUES(signal_text),concern_text=VALUES(concern_text),example_features=VALUES(example_features),action_text=VALUES(action_text),ilmb_rule=VALUES(ilmb_rule),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_research_gap(gap_id,question_title,research_question,candidate_variables,required_study_design,priority_text) VALUES
('GAP-001','Durable treatment-free remission','What biological conditions predict sustained remission after treatment withdrawal?','TRM, keratinocyte memory, stromal state, systemic drivers','Longitudinal multi-omic + clinical studies','High'),
('GAP-002','Resident memory T-cell extinction','Can pathogenic skin TRM be selectively extinguished or reprogrammed?','CD69/CD103/TRM cytokine output','Human tissue intervention studies','High'),
('GAP-003','Keratinocyte inflammatory memory','Which epigenetic states persist after visible clearance and are they reversible?','Chromatin/transcriptomic state','Paired lesion-resolved-normal skin studies','High'),
('GAP-004','Non-drug pathway modifiers','Which lifestyle/neuropsychological interventions measurably alter immune/skin pathways?','HRV, cytokines, lesion metrics','Controlled mechanistic trials','High'),
('GAP-005','EMDR → psoriasis bridge','Does EMDR change autonomic/neuroimmune markers and skin disease in trauma-linked psoriasis patients?','SUD/VOC/HRV + PASI/BSA/site metrics','Pre-registered clinical mechanistic study','Research'),
('GAP-006','GPP endotypes','How do IL36RN/CARD14/AP1S3/MPO genotypes map to treatment response?','Genotype + flare phenotype + GPPGA','Prospective registries/trials','High'),
('GAP-007','Subtype-specific digital phenotyping','Can standardized images reliably distinguish phenotype/site activity longitudinally?','Image features + clinician labels','Validated imaging cohorts','Medium'),
('GAP-008','Cure definition','What duration and molecular state are sufficient to call psoriasis cured rather than controlled?','Treatment-free time + biological normalization','Consensus + prospective follow-up','Foundational')
ON DUPLICATE KEY UPDATE question_title=VALUES(question_title),research_question=VALUES(research_question),candidate_variables=VALUES(candidate_variables),required_study_design=VALUES(required_study_design),priority_text=VALUES(priority_text);
