-- ILoveMyBody Phase 106 split seed
-- Extracted verbatim from canonical Phase 106 migration artifact.

INSERT INTO ilb_psoriasis_treatment_class(class_id,class_name,route_or_type,mechanism_summary,typical_role,major_safety_theme,governance_text,source_url) VALUES
('TXC-001','Emollients/barrier care','Topical supportive','Barrier hydration; symptom/scale support','Mild disease/supportive across phenotypes','Not disease-modifying alone in moderate-severe disease','Routine adjunct','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-002','Topical corticosteroids','Topical anti-inflammatory','Broad anti-inflammatory transcriptional effects','Many plaque/site presentations with site-specific potency choices','Skin atrophy and other local/systemic risks depend on potency/site/duration','Guideline-based','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-003','Vitamin D analogues','Topical','Keratinocyte differentiation and immune modulation','Plaque psoriasis','Irritation/hypercalcemia risk if excessive systemic exposure','Guideline-based','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-004','Topical nonsteroid agents','Topical','Examples include PDE4/AhR/retinoid pathways','Site-appropriate mild/moderate disease','Agent-specific safety','Guideline-based','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-005','NB-UVB / targeted UVB','Phototherapy','Immune and epidermal effects of UVB','Widespread plaque/guttate and selected sites','Burn/photoaging; regimen-dependent','Evidence-based','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-006','Methotrexate','Traditional systemic','Folate-pathway/immune effects','Moderate-severe psoriasis/PsA context','Hepatic, marrow, pregnancy and interaction risks','Medical monitoring required','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-007','Cyclosporine','Traditional systemic','Calcineurin inhibition','Rapid control of severe disease in selected patients','Renal/BP/infection/malignancy risks; usually limited duration','Medical monitoring required','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-008','Acitretin','Oral retinoid','Retinoid receptor effects on keratinization','Severe plaque/pustular contexts','Highly teratogenic; lipid/liver/mucocutaneous risks','Medical monitoring required','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-009','PDE4 inhibition','Oral/topical small molecule','PDE4 inhibition','Plaque and/or PsA depending agent','GI/weight/mood or local effects agent-specific','Medical treatment','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-010','TYK2 inhibition','Oral small molecule','Selective TYK2 signaling inhibition','Moderate-severe plaque psoriasis','Agent-specific infection/lab risks','Medical treatment','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-011','TNF inhibition','Biologic','Blocks TNF-alpha','Plaque psoriasis/PsA','Serious infection and class-specific risks','Medical screening/monitoring','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-012','IL-12/23 inhibition','Biologic','Blocks p40 shared subunit','Plaque psoriasis/PsA','Infection and agent-specific risks','Medical screening/monitoring','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-013','IL-17 pathway inhibition','Biologic','Blocks IL-17A, IL-17A/F, or receptor','Plaque psoriasis/PsA','Infection/candidiasis; IBD considerations vary by agent','Medical screening/monitoring','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-014','IL-23 inhibition','Biologic','Blocks IL-23 p19','Plaque psoriasis/PsA for selected agents','Infection and agent-specific risks','Medical screening/monitoring','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('TXC-015','IL-36 receptor inhibition','Biologic','Blocks IL-36 receptor','Generalized pustular psoriasis','Infection/hypersensitivity and agent-specific risks','GPP-specific therapy','https://www.aad.org/member/clinical-quality/guidelines/psoriasis')
ON DUPLICATE KEY UPDATE class_name=VALUES(class_name),mechanism_summary=VALUES(mechanism_summary),typical_role=VALUES(typical_role),major_safety_theme=VALUES(major_safety_theme),governance_text=VALUES(governance_text),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_medicine_reference(drug_id,generic_name,class_name,route_text,mechanism_text,psoriasis_role,major_safety_theme,source_url) VALUES
('DRUG-001','Calcipotriene/calcipotriol','Vitamin D analogue','Topical','Vitamin D receptor agonism','Plaque psoriasis; often combined with steroid','Local irritation; calcium effects with excessive use','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('DRUG-002','Tazarotene','Retinoid','Topical','Retinoid receptor modulation','Plaque psoriasis','Irritation; pregnancy contraindication','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('DRUG-003','Roflumilast','PDE4 inhibitor','Topical','PDE4 inhibition','Plaque/inverse depending formulation/approval','Local/systemic agent-specific effects','https://www.aad.org/public/diseases/psoriasis/treatment/treatment'),
('DRUG-004','Tapinarof','AhR agonist','Topical','Aryl hydrocarbon receptor agonism','Plaque psoriasis','Folliculitis/contact effects possible','https://www.aad.org/public/diseases/psoriasis/treatment/treatment'),
('DRUG-005','Methotrexate','Antimetabolite/systemic immunomodulator','Oral/injectable','Folate pathway and immunomodulatory effects','Moderate-severe psoriasis/PsA','Hepatic, marrow, teratogenicity; monitoring required','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('DRUG-006','Cyclosporine','Calcineurin inhibitor','Oral','T-cell calcineurin inhibition','Short-term rapid control in selected severe disease','Nephrotoxicity, hypertension, infection, interactions','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('DRUG-007','Acitretin','Systemic retinoid','Oral','Retinoid receptor modulation','Severe plaque and pustular forms','Profound teratogenicity; lipids/liver; mucocutaneous effects','https://www.aad.org/public/diseases/psoriasis/treatment/treatment'),
('DRUG-008','Apremilast','PDE4 inhibitor','Oral','PDE4 inhibition','Plaque psoriasis/PsA','GI effects, weight change, mood warning considerations','https://www.aad.org/member/clinical-quality/guidelines/psoriasis'),
('DRUG-009','Deucravacitinib','TYK2 inhibitor','Oral','Selective TYK2 inhibition','Moderate-severe plaque psoriasis','Infection/agent-specific lab monitoring','https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2022'),
('DRUG-010','Icotrokinra','IL-23 receptor targeted oral peptide','Oral','Blocks IL-23 receptor signaling','Plaque psoriasis','Current label/monitoring should be checked before use','https://www.aad.org/public/diseases/psoriasis/treatment/treatment'),
('DRUG-011','Etanercept','TNF inhibitor','Biologic injection','TNF blockade','Plaque psoriasis/PsA','Serious infection and class warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-012','Adalimumab','TNF inhibitor','Biologic injection','TNF blockade','Plaque psoriasis/PsA','Serious infection and class warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-013','Infliximab','TNF inhibitor','IV biologic','TNF blockade','Plaque psoriasis/PsA','Serious infection; infusion/class warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-014','Certolizumab pegol','TNF inhibitor','Biologic injection','TNF blockade','Plaque psoriasis/PsA','Serious infection and class warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-015','Ustekinumab','IL-12/23 p40 inhibitor','Biologic injection','Blocks IL-12/23 p40','Plaque psoriasis/PsA','Infection and agent-specific warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-016','Secukinumab','IL-17A inhibitor','Biologic injection','Neutralizes IL-17A','Plaque psoriasis/PsA','Infection/candidiasis; IBD caution context','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-017','Ixekizumab','IL-17A inhibitor','Biologic injection','Neutralizes IL-17A','Plaque psoriasis/PsA','Infection/candidiasis; IBD caution context','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-018','Brodalumab','IL-17 receptor A inhibitor','Biologic injection','Blocks IL-17RA signaling','Plaque psoriasis','Agent-specific boxed warning and infection risks','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-019','Bimekizumab','IL-17A/F inhibitor','Biologic injection','Neutralizes IL-17A and IL-17F','Plaque psoriasis/PsA','Candidiasis/infection and agent-specific warnings','https://www.psoriasis.org/current-biologics-on-the-market/'),
('DRUG-020','Guselkumab','IL-23 p19 inhibitor','Biologic injection','Blocks IL-23 p19','Plaque psoriasis/PsA','Infection and agent-specific warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-021','Risankizumab','IL-23 p19 inhibitor','Biologic injection','Blocks IL-23 p19','Plaque psoriasis/PsA','Infection and agent-specific warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-022','Tildrakizumab','IL-23 p19 inhibitor','Biologic injection','Blocks IL-23 p19','Plaque psoriasis','Infection and agent-specific warnings','https://www.aad.org/public/diseases/psoriasis/treatment/medications/biologics'),
('DRUG-023','Spesolimab-sbzo','IL-36 receptor antagonist','IV/SC biologic','Blocks IL-36 receptor','Generalized pustular psoriasis','Infection/hypersensitivity/agent-specific neurologic warnings; label-specific monitoring','https://www.accessdata.fda.gov/scripts/opdlisting/oopd/detailedIndex.cfm?cfgridkey=651618')
ON DUPLICATE KEY UPDATE generic_name=VALUES(generic_name),class_name=VALUES(class_name),mechanism_text=VALUES(mechanism_text),psoriasis_role=VALUES(psoriasis_role),major_safety_theme=VALUES(major_safety_theme),source_url=VALUES(source_url);
