-- Phase 126: Psoriasis cross-modality intersection matrix
-- Purpose: expose convergence across modalities without promoting weak evidence to mechanism.

CREATE TABLE IF NOT EXISTS ilb_psoriasis_cross_modality_intersection (
  intersection_id VARCHAR(96) PRIMARY KEY,
  modality_code VARCHAR(96) NOT NULL,
  control_zone VARCHAR(64) NOT NULL,
  target_node VARCHAR(128) NOT NULL,
  direction_code VARCHAR(32) NOT NULL,
  intersection_class VARCHAR(32) NOT NULL,
  evidence_status VARCHAR(32) NOT NULL,
  human_psoriasis_evidence VARCHAR(32) NOT NULL,
  mechanism_statement TEXT NOT NULL,
  claim_boundary TEXT NOT NULL,
  required_measurement TEXT NOT NULL,
  redundancy_group VARCHAR(64) NULL,
  complementary_group VARCHAR(64) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO ilb_psoriasis_cross_modality_intersection
(intersection_id,modality_code,control_zone,target_node,direction_code,intersection_class,evidence_status,human_psoriasis_evidence,mechanism_statement,claim_boundary,required_measurement,redundancy_group,complementary_group)
VALUES
('P126-NBUVB-IMMUNE','NB_UVB','IMMUNE','cutaneous inflammatory drive / IL23-Th17-IL17 network','DOWN','DIRECT_CONVERGENCE','ESTABLISHED','DIRECT','Phototherapy has established psoriasis efficacy and suppresses cutaneous inflammatory activity while affecting epidermal hyperplasia.','Do not reduce its action to one cytokine or assume durability.','delivered UVB dose; PASI/BSA; target lesion geometry','DIRECT_SKIN_CONTROL','CORE_IK'),
('P126-NBUVB-EPI','NB_UVB','EPIDERMAL','keratinocyte hyperproliferation / epidermal thickness','NORMALIZE','DIRECT_CONVERGENCE','ESTABLISHED','DIRECT','NB-UVB directly addresses abnormal epidermal growth in psoriasis.','Requires controlled phototherapy exposure and safety governance.','target thickness; V_excess; standardized photo','DIRECT_SKIN_CONTROL','CORE_IK'),
('P126-INDIR-IMMUNE','INDIRUBIN','IMMUNE','IL17A-TAK1-CCL20 keratinocyte feedback','DOWN','DIRECT_CONVERGENCE','SUPPORTED','DIRECT','Indirubin/indigo naturalis has human psoriasis efficacy and mechanistic evidence attenuating inflammatory keratinocyte feedback.','Formulation-specific evidence; do not generalize to all indigo products or traditional medicine.','defined formulation/exposure; PASI; CCL20/IL17-linked markers where available','DIRECT_MOLECULE_IK','CORE_IK'),
('P126-INDIR-EPI','INDIRUBIN','EPIDERMAL','EGFR/CDC25B; PCNA; cell-cycle/differentiation','NORMALIZE','DIRECT_CONVERGENCE','SUPPORTED','DIRECT','Indirubin inhibits epidermal growth signaling and is associated with reduced proliferation and improved differentiation markers.','Do not infer barrier normalization or durable cure from PASI response alone.','PCNA/Ki67; involucrin; lesion thickness; V_excess','DIRECT_MOLECULE_IK','CORE_IK'),
('P126-CURC-IMMUNE','CURCUMIN','IMMUNE','IL17/IL23/TNF inflammatory axis','DOWN','DIRECT_CONVERGENCE','PRELIMINARY','DIRECT_SMALL_TRIAL','Small topical psoriasis pilot reported reduced IL17/IL23/IL22/TNF expression.','Very small human study; formulation-dependent; not treatment-standard evidence.','defined formulation; PASI; cytokine markers','DIRECT_MOLECULE_IK','CORE_IK'),
('P126-CURC-EPI','CURCUMIN','EPIDERMAL','Ki67/proliferation and differentiation markers','NORMALIZE','DIRECT_CONVERGENCE','PRELIMINARY','DIRECT_SMALL_TRIAL','Small topical pilot reported reduced Ki67 alongside clinical lesion improvement.','Pilot evidence only.','Ki67; target lesion geometry','DIRECT_MOLECULE_IK','CORE_IK'),
('P126-BARRIER-BARRIER','BARRIER_CARE','BARRIER','stratum-corneum resistance / TEWL / fissure-scale state','NORMALIZE','DIRECT_CONVERGENCE','SUPPORTED','DIRECT_SUPPORT','Barrier-directed care acts directly on downstream physical barrier state.','Barrier improvement is not proof of immune normalization.','TEWL; hydration; fissure/scale; photos','BARRIER_SUPPORT','CORE_B'),
('P126-VITD-EPI','VITAMIN_D','EPIDERMAL','VDR-linked keratinocyte differentiation','NORMALIZE','BIOLOGICAL_CONVERGENCE','MIXED_SUPPORTED','MIXED','Vitamin-D/VDR biology intersects keratinocyte differentiation and immune regulation; psoriasis supplementation outcomes are inconsistent.','Use only when measured deficiency/clinical indication exists; no universal psoriasis dosing claim.','25OH-D; PASI; differentiation markers where research-grade','NUTRIENT_MODIFIER','COND_VITD'),
('P126-VITD-IMMUNE','VITAMIN_D','IMMUNE','cytokine regulation','NORMALIZE','BIOLOGICAL_CONVERGENCE','MIXED_SUPPORTED','MIXED','Vitamin D has immunomodulatory biology and some psoriasis adjunct evidence, especially with phototherapy.','Do not infer cytokine correction from serum 25OH-D alone.','25OH-D; relevant cytokines; PASI','NUTRIENT_MODIFIER','COND_VITD'),
('P126-PROBIO-IMMUNE','PROBIOTIC','IMMUNE','gut-systemic inflammatory modifiers / CRP','DOWN','SYSTEM_CONVERGENCE','PRELIMINARY_SUPPORTED','DIRECT_META_SIGNAL','Probiotic RCT meta-analyses report PASI and CRP improvement, indicating a gut-systemic inflammatory intersection.','No universal strain, dose, or gut-to-IL17 coefficient.','defined strain/dose; PASI; CRP; GI state','GUT_MODIFIER','COND_MICRO'),
('P126-METAB-IMMUNE','METABOLIC_CORRECTION','IMMUNE','metabolic inflammatory amplification','DOWN','SYSTEM_CONVERGENCE','SUPPORTED_CONDITIONAL','DIRECT_SELECTED','Weight/metabolic correction can reduce psoriasis activity in selected overweight/obese populations.','Conditional on measured metabolic state; not universal.','weight/waist; metabolic labs; PASI','METABOLIC_MODIFIER','COND_METAB'),
('P126-MINDFUL-ANS','MINDFULNESS_CBT','NEURO_AUTONOMIC','threat/stress/autonomic state','NORMALIZE','UPSTREAM_CONVERGENCE','SUPPORTED','DIRECT','Multiple psoriasis RCTs show short-term improvement in skin severity and quality of life with mindfulness/meditation.','Clinical improvement does not prove IL17 mediation.','stress scale; HRV if used; PASI/BSA','STRESS_REGULATION','COND_ANS'),
('P126-EMDR-ANS','EMDR','NEURO_AUTONOMIC','memory-linked threat/distress/autonomic arousal','NORMALIZE','UPSTREAM_CONVERGENCE','SUPPORTED_GENERAL_PRELIMINARY_PSO','INDIRECT','EMDR directly targets distressing memory/threat processing and may alter autonomic arousal.','No direct psoriasis or IL17 mechanism established; downstream skin effects must be measured.','SUD; HRV; stress; PASI/BSA/target lesion','STRESS_REGULATION','COND_ANS'),
('P126-BREATH-ANS','BREATHING','NEURO_AUTONOMIC','respiratory-autonomic regulation','NORMALIZE','UPSTREAM_CONVERGENCE','PLAUSIBLE','NO_DIRECT_PSO','Breathing practices can alter autonomic physiology in other contexts and overlap the same ANS/HPA control zone.','No psoriasis-specific direct-treatment evidence; mechanism claim requires HRV/cortisol plus skin change.','respiratory rate; HRV; stress; sleep; PASI','STRESS_REGULATION','COND_ANS'),
('P126-SLEEP-ANS','SLEEP_CORRECTION','NEURO_AUTONOMIC','sleep/circadian-neuroimmune state','NORMALIZE','UPSTREAM_CONVERGENCE','ASSOCIATIVE_SUPPORTED','INDIRECT','Sleep disturbance is common in psoriasis and overlaps stress/autonomic/neuroimmune control.','Causal psoriasis-treatment effect remains incompletely established.','sleep log/PSQI; itch; stress; PASI','STRESS_REGULATION','COND_SLEEP'),
('P126-ACU-ANS','ACUPUNCTURE','NEURO_AUTONOMIC','neural/autonomic modulation','NORMALIZE','PLAUSIBLE_CONVERGENCE','LOW_CERTAINTY','MIXED_DIRECT','Acupuncture studies suggest possible psoriasis benefit and plausible neural/immune modulation.','Point-specific psoriasis node chain is not quantitatively established; evidence quality is mixed.','defined points/protocol; HRV if used; PASI; lesion geometry','NEURAL_ADJUNCT','RESEARCH_ADJUNCT'),
('P126-ACU-IMMUNE','ACUPUNCTURE','IMMUNE','immune-inflammatory modulation','UNKNOWN','PLAUSIBLE_CONVERGENCE','LOW_CERTAINTY','MIXED_DIRECT','Some acupuncture psoriasis studies report clinical improvement, but direct mediator evidence is insufficient.','Do not assign IL17 lowering to a point without measurement.','defined protocol; cytokine markers if tested; PASI','NEURAL_ADJUNCT','RESEARCH_ADJUNCT'),
('P126-HOME-OUTCOME','HOMEOPATHY','NEURO_AUTONOMIC','individual symptom/emotional pattern and clinical outcome','UNKNOWN','OUTCOME_CONVERGENCE','PRELIMINARY','DIRECT_SMALL_RCT','A small double-blind psoriasis RCT reported greater PASI improvement than placebo after six months.','No established molecular mechanism; outcome signal must not be converted into IL17/keratinocyte coefficients.','remedy/exposure; PASI; emotional state; mediator measures only if prospectively tested','NARRATIVE_OUTCOME','VERIFICATION_LAYER'),
('P126-BACH-EMO','BACH','NEURO_AUTONOMIC','emotional-state constructs','UNKNOWN','NARRATIVE_CONVERGENCE','NO_PSO_MECHANISM','NO_DIRECT_PSO','Bach framework overlaps emotional-state monitoring but has no established psoriasis biological mechanism.','Verification/narrative only.','emotional-state measure; independent skin outcomes','NARRATIVE_OUTCOME','VERIFICATION_LAYER'),
('P126-HAY-EMO','LOUISE_HAY','NEURO_AUTONOMIC','fear of hurt / self-criticism / emotional shutdown themes','UNKNOWN','NARRATIVE_CONVERGENCE','ANECDOTAL','NO_DIRECT_PSO','Louise Hay themes overlap threat/meaning/self-evaluation constructs identified in some narratives.','Must not be promoted to psoriasis causation or cytokine biology.','coded narrative themes; stress; independent skin outcomes','NARRATIVE_OUTCOME','VERIFICATION_LAYER'),
('P126-REDI-EMO','REDIKALL','NEURO_AUTONOMIC','emotional meaning / threat constructs','UNKNOWN','NARRATIVE_CONVERGENCE','HYPOTHESIS','NO_DIRECT_PSO','Redikall overlaps emotional/threat interpretation layers.','No demonstrated psoriasis molecular mechanism.','coded emotional state; independent skin outcomes','NARRATIVE_OUTCOME','VERIFICATION_LAYER'),
('P126-HORM-IMMUNE','ENDOCRINE','IMMUNE','cortisol/insulin/thyroid/prolactin/sex-hormone modifiers','NORMALIZE','SYSTEM_CONVERGENCE','ASSOCIATIVE','INDIRECT','Endocrine states intersect immune and epidermal biology and correlate with psoriasis activity in specific contexts.','Hormone treatment is not a psoriasis intervention without independent clinical indication.','clinically indicated hormone/metabolic measures; disease trajectory','ENDOCRINE_MODIFIER','COND_ENDOCRINE')
ON DUPLICATE KEY UPDATE evidence_status=VALUES(evidence_status),human_psoriasis_evidence=VALUES(human_psoriasis_evidence),mechanism_statement=VALUES(mechanism_statement),claim_boundary=VALUES(claim_boundary),required_measurement=VALUES(required_measurement);

CREATE OR REPLACE VIEW v_ilb_psoriasis_intersection_zones AS
SELECT control_zone, COUNT(DISTINCT modality_code) AS modality_count,
       SUM(intersection_class IN ('DIRECT_CONVERGENCE','BIOLOGICAL_CONVERGENCE','SYSTEM_CONVERGENCE','UPSTREAM_CONVERGENCE')) AS biologically_grounded_links,
       SUM(intersection_class='NARRATIVE_CONVERGENCE') AS narrative_links
FROM ilb_psoriasis_cross_modality_intersection
GROUP BY control_zone;
