-- Phase 111: Psoriasis IL-17 -> keratinocyte population -> epidermal geometry
-- Formula-first rule: DERIVE -> PREDICT -> VERIFY. No unsourced numeric coefficients.

CREATE TABLE IF NOT EXISTS ilb_psoriasis_keratinocyte_equation (
  equation_id VARCHAR(64) PRIMARY KEY,
  equation_code VARCHAR(64) NOT NULL UNIQUE,
  layer_name VARCHAR(64) NOT NULL,
  equation_latex TEXT NOT NULL,
  derivation_class VARCHAR(64) NOT NULL,
  closure_status VARCHAR(64) NOT NULL,
  biological_basis TEXT NOT NULL,
  unresolved_primitives TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ilb_psoriasis_keratinocyte_primitive (
  primitive_code VARCHAR(64) PRIMARY KEY,
  primitive_name VARCHAR(128) NOT NULL,
  unit_text VARCHAR(64) NOT NULL,
  source_rule VARCHAR(128) NOT NULL,
  allowed_origin VARCHAR(64) NOT NULL,
  value_num DECIMAL(30,12) NULL,
  source_note TEXT NULL,
  context_requirement TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'UNRESOLVED'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO ilb_psoriasis_keratinocyte_equation
(equation_id,equation_code,layer_name,equation_latex,derivation_class,closure_status,biological_basis,unresolved_primitives)
VALUES
('PSO-KC-E01','ACT1_SIGNAL_BALANCE','SIGNALING',
'dA/dt = k_act * O * (A_tot - A) - k_deact * A',
'MASS_ACTION_STYLE','STRUCTURE_DERIVED',
'Occupied IL-17 receptor complexes recruit/activate ACT1/TRAF6 signaling; IL-17RA/RC signaling activates NF-kB and MAPK pathways. Exact transfer kinetics are not fully quantified in human psoriatic epidermis.',
'k_act,k_deact,A_tot'),

('PSO-KC-E02','CYCLING_POOL_BALANCE','CELL_POPULATION',
'dN_p/dt = r_self * N_p - r_commit * N_p - r_apop_p * N_p',
'POPULATION_CONSERVATION','STRUCTURE_DERIVED',
'Proliferative keratinocyte compartment changes by self-renewing division, commitment into differentiation and apoptosis.',
'r_self,r_commit,r_apop_p'),

('PSO-KC-E03','DIFFERENTIATED_POOL_BALANCE','CELL_POPULATION',
'dN_d/dt = r_commit * N_p - r_corn * N_d - r_apop_d * N_d',
'POPULATION_CONSERVATION','STRUCTURE_DERIVED',
'Differentiated viable epidermis is supplied by committed proliferative cells and depleted by cornification and loss.',
'r_commit,r_corn,r_apop_d'),

('PSO-KC-E04','CORNEUM_POOL_BALANCE','CELL_POPULATION',
'dN_c/dt = r_corn * N_d - r_shed * N_c',
'POPULATION_CONSERVATION','STRUCTURE_DERIVED',
'Stratum corneum cell pool is generated by cornification and depleted by desquamation/shedding.',
'r_corn,r_shed'),

('PSO-KC-E05','CELL_CYCLE_RATE','CELL_KINETICS',
'r_cycle = ln(2) / T_cycle',
'FIRST_ORDER_FROM_DOUBLING_TIME','DERIVED',
'For an exponentially renewing cycling compartment, doubling/cycle-time information can be converted into a rate only when the population definition and assumptions match.',
'T_cycle'),

('PSO-KC-E06','EPIDERMAL_VOLUME','GEOMETRY',
'V_epi = N_p*v_p + N_d*v_d + N_c*v_c',
'GEOMETRIC_SUM','DERIVED',
'Epidermal volume is the sum of compartment cell volumes under a compartment-averaged geometry model.',
'N_p,N_d,N_c,v_p,v_d,v_c'),

('PSO-KC-E07','EPIDERMAL_THICKNESS','GEOMETRY',
'h_epi = V_epi / A_lesion',
'GEOMETRY','DERIVED',
'Thickness equals volume divided by lesion surface area for the modeled tissue patch.',
'V_epi,A_lesion'),

('PSO-KC-E08','EXCESS_PLAQUE_VOLUME','GEOMETRY',
'V_excess = A_lesion * max(h_epi - h_normal, 0)',
'GEOMETRY','DERIVED',
'Physical excess plaque/epidermal volume can be represented as lesion area times excess epidermal thickness above matched normal skin.',
'A_lesion,h_epi,h_normal'),

('PSO-KC-E09','KERATINOCYTE_SIGNAL_TO_CYCLE_GATE','SIGNALING_TO_CELL_CYCLE',
'r_self = F(A,NFkB,ERK,p38,JNK,YAP,AREG,EGFR,STAT3,other_inputs)',
'BIOLOGICAL_TRANSFER_FUNCTION','NOT_CLOSED',
'IL-17A promotes keratinocyte proliferation through ACT1-dependent signaling and pathways including NF-kB/MAPK, EGFR transactivation and YAP-AREG; the exact quantitative human transfer function is not established and must not be invented.',
'full reaction-network rate constants and abundances')
ON DUPLICATE KEY UPDATE
 equation_latex=VALUES(equation_latex), closure_status=VALUES(closure_status), biological_basis=VALUES(biological_basis), unresolved_primitives=VALUES(unresolved_primitives);

INSERT INTO ilb_psoriasis_keratinocyte_primitive
(primitive_code,primitive_name,unit_text,source_rule,allowed_origin,value_num,source_note,context_requirement,status)
VALUES
('T_CYCLE','Cycling keratinocyte cycle time','h','Measured in correctly matched human epidermal compartment','SOURCE_OR_PERSON_MEASURED',NULL,NULL,'Must identify lesional/non-lesional, cycling-pool definition, method, and disease state. Historical 36 h psoriasis value is context only, not universal.','UNRESOLVED'),
('R_COMMIT','Proliferative-to-differentiated commitment rate','1/time','Derived from compartment transit/lineage kinetics','SOURCE_OR_DERIVED',NULL,NULL,'Must use matched epidermal compartment and state.','UNRESOLVED'),
('R_CORN','Differentiated-to-corneocyte transition rate','1/time','Derived from transit time','SOURCE_OR_DERIVED',NULL,NULL,'Must use matched viable epidermal compartment.','UNRESOLVED'),
('R_SHED','Corneocyte shedding rate','1/time','Derived from stratum-corneum residence time','SOURCE_OR_DERIVED',NULL,NULL,'Must use matched lesion/site/hydration context.','UNRESOLVED'),
('V_P','Mean proliferative keratinocyte volume','m^3/cell','Geometry/morphometry','SOURCE_OR_PERSON_GEOMETRY',NULL,NULL,'Must state measurement method and compartment.','UNRESOLVED'),
('V_D','Mean differentiated keratinocyte volume','m^3/cell','Geometry/morphometry','SOURCE_OR_PERSON_GEOMETRY',NULL,NULL,'Must state measurement method and compartment.','UNRESOLVED'),
('V_C','Mean corneocyte volume','m^3/cell','Geometry/morphometry','SOURCE_OR_PERSON_GEOMETRY',NULL,NULL,'Must state measurement method and compartment.','UNRESOLVED'),
('A_LESION','Lesion surface area','m^2','Direct geometry','PERSON_MEASURED',NULL,NULL,'Measured from calibrated imaging or traced area.','UNRESOLVED'),
('H_NORMAL','Matched normal epidermal thickness','m','Direct geometry or sourced matched reference','SOURCE_OR_PERSON_MEASURED',NULL,NULL,'Prefer same patient and anatomical site.','UNRESOLVED'),
('K_ACT','Occupied-receptor to ACT1 activation kinetic constant','context dependent','Reaction-network kinetics','SOURCE_ONLY',NULL,NULL,'Human keratinocyte context required.','UNRESOLVED'),
('K_DEACT','ACT1-pathway deactivation kinetic constant','1/time','Reaction-network kinetics','SOURCE_ONLY',NULL,NULL,'Human keratinocyte context required.','UNRESOLVED')
ON DUPLICATE KEY UPDATE primitive_name=VALUES(primitive_name), context_requirement=VALUES(context_requirement);

CREATE OR REPLACE VIEW v_ilb_psoriasis_keratinocyte_geometry_readiness AS
SELECT
  (SELECT COUNT(*) FROM ilb_psoriasis_keratinocyte_equation) AS equations,
  (SELECT SUM(closure_status='DERIVED') FROM ilb_psoriasis_keratinocyte_equation) AS fully_derived_equations,
  (SELECT SUM(closure_status='STRUCTURE_DERIVED') FROM ilb_psoriasis_keratinocyte_equation) AS structure_derived_equations,
  (SELECT SUM(closure_status='NOT_CLOSED') FROM ilb_psoriasis_keratinocyte_equation) AS not_closed_equations,
  (SELECT COUNT(*) FROM ilb_psoriasis_keratinocyte_primitive) AS primitives,
  (SELECT SUM(value_num IS NOT NULL) FROM ilb_psoriasis_keratinocyte_primitive) AS numeric_primitives,
  'IL17 occupancy -> signaling structure -> compartment balances -> epidermal geometry; quantitative signal-to-cycle transfer remains unresolved' AS governance_note;
