INSERT INTO ilb_psoriasis_phenotype(phenotype_id,name,record_type,synonyms,core_appearance,typical_distribution,course_text,dominant_biology_note,safety_class,notes_text,source_url) VALUES
('PSO-PH-001','Chronic plaque psoriasis','Phenotype','Plaque / psoriasis vulgaris','Well-demarcated raised inflammatory plaques with scale; most common phenotype.','Scalp, elbows, knees, trunk, umbilicus, lumbosacral area; any site possible','Chronic relapsing','IL-23/IL-17 dominant adaptive-immune/keratinocyte loop','Not an emergency unless unstable erythroderma, infection, etc.','Can coexist with nail, scalp, inverse, genital and joint disease.','https://www.psoriasis.org/locations-and-types/'),
('PSO-PH-002','Guttate psoriasis','Phenotype','Guttate','Numerous small round/drop-like scaly papules/plaques, often abrupt onset.','Trunk and proximal limbs commonly','Acute/subacute; may resolve or evolve to plaque disease','Strong association with recent streptococcal infection in a subset','Routine unless severe/systemically unwell','Often starts in childhood/young adulthood but can occur at any age.','https://www.psoriasis.org/guttate/'),
('PSO-PH-003','Inverse psoriasis','Phenotype','Flexural / intertriginous','Smooth shiny inflamed patches, usually with little scale because folds are moist.','Axillae, inframammary folds, groin/genital folds, gluteal cleft','Chronic/recurrent','Psoriatic inflammation modified by friction, moisture and occlusion','High-impact site; evaluate infection mimics','May coexist with plaque psoriasis elsewhere.','https://www.psoriasis.org/inverse-psoriasis/'),
('PSO-PH-004','Generalized pustular psoriasis','Phenotype','GPP / von Zumbusch','Widespread sterile pustules with systemic inflammatory illness possible.','Generalized','Acute flares; can recur','IL-36/neutrophil-autoinflammatory axis is especially important','URGENT / potentially life-threatening','Genetically and biologically distinct from plaque psoriasis in important respects.','https://pubmed.ncbi.nlm.nih.gov/39732527/'),
('PSO-PH-005','Palmoplantar pustulosis','Phenotype','PP / PPPP','Chronic sterile pustules of palms and/or soles, with scaling/fissuring.','Palms and soles','Chronic','Pustular/neutrophilic biology; smoking association is strong observationally','High-impact functional site','Relationship to plaque psoriasis differs across patients.','https://www.psoriasis.org/pustular/'),
('PSO-PH-006','Acrodermatitis continua of Hallopeau','Phenotype','ACH','Rare sterile pustular disease of distal fingers/toes, often involving nail apparatus.','Fingertips, toes, periungual/nail unit','Chronic/refractory','Pustular/IL-36-related biology in some patients','Specialist review; tissue/nail damage risk','Very rare localized pustular phenotype.','https://www.psoriasis.org/pustular/'),
('PSO-PH-007','Erythrodermic psoriasis','Phenotype','Erythrodermic','Near-generalized erythema/discoloration with extensive scaling/exfoliation and systemic effects.','Usually >80–90% BSA','Acute or progressive severe disease','Systemic inflammatory and barrier failure state','URGENT / potentially life-threatening','Can disturb fluid, temperature and cardiovascular homeostasis.','https://www.psoriasis.org/erythrodermic-psoriasis/')
ON DUPLICATE KEY UPDATE name=VALUES(name),core_appearance=VALUES(core_appearance),safety_class=VALUES(safety_class),notes_text=VALUES(notes_text),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_site(site_id,site_name,site_class,common_features,preferred_measurements,key_differentials,clinical_note,source_url) VALUES
('PSO-SITE-001','Scalp','High-impact site','Plaque-type disease often extends beyond hairline; fine to thick adherent scale.','PSSI; PGA; itch NRS; standardized photos','Seborrheic dermatitis, eczema, tinea capitis','Hair and treatment-vehicle issues matter; temporary hair shedding can occur with severe disease.','https://www.psoriasis.org/scalp/'),
('PSO-SITE-002','Nails','High-impact site','Pitting, onycholysis, subungual hyperkeratosis, discoloration, crumbling/deformation.','NAPSI; number of nails; pain/function','Onychomycosis, lichen planus, trauma','Strong association with PsA; nail-unit location affects manifestation.','https://www.psoriasis.org/hands-feet-nails/'),
('PSO-SITE-003','Palms/soles','High-impact site','Hyperkeratotic plaques, fissures and/or pustules; often highly disabling.','PPPASI or site PGA; fissure count; pain; function','Tinea manuum/pedis, eczema, contact dermatitis','Small BSA can still represent severe functional disease.','https://www.psoriasis.org/palmoplantar-psoriasis/'),
('PSO-SITE-004','Genitals','High-impact site','Plaque or inverse morphology; less scale in folds; soreness/itch/fissuring possible.','Genital PGA/sPGA; DLQI/sexual-impact PROs','Candidiasis, tinea, dermatitis, lichen sclerosus, STI-related eruptions','High quality-of-life burden irrespective of BSA.','https://www.psoriasis.org/genitals/'),
('PSO-SITE-005','Skin folds','High-impact site','Smooth erythematous/dyschromic plaques with minimal scale.','Site PGA; pain/itch','Intertrigo, candidiasis, erythrasma, tinea','Moisture, friction and occlusion can amplify symptoms.','https://www.psoriasis.org/inverse-psoriasis/'),
('PSO-SITE-006','Face','High-impact site','Thin plaques or sebopsoriasis-like lesions; visible-site burden.','Facial PGA; DLQI','Seborrheic dermatitis, lupus, eczema, tinea faciei','Treatment sensitivity differs because facial skin is thin.','https://dermnetnz.org/topics/psoriasis')
ON DUPLICATE KEY UPDATE site_name=VALUES(site_name),common_features=VALUES(common_features),preferred_measurements=VALUES(preferred_measurements),clinical_note=VALUES(clinical_note),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_morphology(morphology_id,term,definition_text,commonly_seen_in,notes_text) VALUES
('MOR-001','Plaque','Raised, well-demarcated inflammatory lesion','Chronic plaque psoriasis','Scale may be silvery-white; colour varies by skin tone.'),
('MOR-002','Papule','Small raised lesion','Guttate / early psoriasis','Often multiple and scaly.'),
('MOR-003','Scale','Excess stratum corneum shedding','Plaque/scalp','May be reduced in moist folds.'),
('MOR-004','Pustule','Sterile pus-filled lesion','GPP/PPP/ACH','Pus reflects neutrophilic inflammation, not bacterial infection by default.'),
('MOR-005','Fissure','Linear crack in thickened skin','Palmoplantar/inverse','Painful; can affect function and secondary infection risk.'),
('MOR-006','Erythroderma','Near-generalized erythema/dyschromia','Erythrodermic psoriasis','Systemic safety state.'),
('MOR-007','Pitting','Punctate depressions in nail plate','Nail psoriasis','Matrix involvement.'),
('MOR-008','Onycholysis','Separation of nail plate from bed','Nail psoriasis','Nail-bed involvement; fungal disease can coexist.'),
('MOR-009','Subungual hyperkeratosis','Keratin accumulation beneath nail','Nail psoriasis','Can thicken and lift nail.'),
('MOR-010','Oil-drop/salmon patch','Yellow-brown translucent nail-bed discoloration','Nail psoriasis','Characteristic but not always present.'),
('MOR-011','Annular configuration','Ring-like lesions','Some pustular/plaque presentations','Pattern descriptor, not a separate disease.'),
('MOR-012','Koebnerized lesions','Psoriasis developing at injury sites','Any cutaneous phenotype','Phenomenon indicates trauma-linked lesion induction.')
ON DUPLICATE KEY UPDATE term=VALUES(term),definition_text=VALUES(definition_text),notes_text=VALUES(notes_text);

INSERT INTO ilb_psoriasis_histopathology(feature_id,feature_name,description_text,frequency_or_role,diagnostic_note,source_url) VALUES
('HIS-001','Hyperkeratosis','Thickened stratum corneum','Common','Supportive, not specific alone','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-002','Parakeratosis','Retention of nuclei in stratum corneum','Common','Often confluent/intermittent','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-003','Hypogranulosis','Reduced granular layer','Common','Classic supportive feature','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-004','Regular psoriasiform acanthosis','Epidermal thickening with elongated rete ridges','Common','Architecture varies with lesion stage','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-005','Suprapapillary thinning','Thin epidermis over dermal papillae','Supportive','Contributes to pinpoint bleeding tendency','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-006','Dilated papillary dermal capillaries','Tortuous/ectatic superficial vessels','Common','Explains erythema and Auspitz phenomenon','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-007','Munro microabscesses','Neutrophils in stratum corneum','Characteristic clue','Not present in every biopsy','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-008','Spongiform pustules of Kogoj','Neutrophils within epidermis','Characteristic clue','Especially prominent in pustular lesions','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-009','Perivascular lymphocytic infiltrate','Superficial dermal inflammatory infiltrate','Common','Nonspecific alone','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-010','Neutrophilic epidermal infiltration','Neutrophils migrate into epidermis','Active/pustular disease','Chemokine-driven','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-011','Spongiosis','Intercellular epidermal edema','Can occur','Does not exclude psoriasis','https://pubmed.ncbi.nlm.nih.gov/34754910/'),
('HIS-012','Papillary dermal edema','Edema in superficial dermis','Can occur','Stage-dependent','https://pubmed.ncbi.nlm.nih.gov/34754910/')
ON DUPLICATE KEY UPDATE feature_name=VALUES(feature_name),description_text=VALUES(description_text),diagnostic_note=VALUES(diagnostic_note),source_url=VALUES(source_url);
