-- Phase 54: governed clinical-service catalogue. Reads or changes no patient-authored record.
START TRANSACTION;
CREATE TABLE IF NOT EXISTS ilb_clinical_service_catalog (
 service_key varchar(80) NOT NULL, display_order smallint unsigned NOT NULL, service_name varchar(180) NOT NULL,
 service_group varchar(80) NOT NULL, primary_inputs varchar(1200) NOT NULL, timeline_output varchar(1000) NOT NULL,
 review_boundary varchar(1500) NOT NULL, status enum('draft','active','retired') NOT NULL DEFAULT 'active',
 PRIMARY KEY(service_key), UNIQUE KEY uq_ilb_service_catalog_order(display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO ilb_clinical_service_catalog(service_key,display_order,service_name,service_group,primary_inputs,timeline_output,review_boundary,status) VALUES
('pathology_laboratory',10,'Pathology & Laboratory Medicine','diagnostics','Test identity, specimen, collection time, result, unit, reporting-lab interval and report document.','Dated measurement; interval position only after exact identity, specimen and unit gates.','Does not diagnose, infer intervals, convert units implicitly or recommend treatment.','active'),
('radiology_imaging',20,'Radiology & Imaging','diagnostics','Study type, body region, modality, performed time, radiologist report, image/document reference and confirmed findings.','Dated imaging event linked to original report.','Does not interpret images or create findings.','active'),
('cardiology',30,'Cardiology','specialty','Vitals, ECG/echo/stress reports, cardiac labs, medicines and confirmed diagnoses.','Dated cardiovascular observations and documents.','Acute chest pain, breathlessness or fainting are emergency pathways.','active'),
('neurology',40,'Neurology','specialty','Examination records, imaging reports, symptoms, medicines and confirmed diagnoses.','Dated neurological observations and source documents.','New weakness, speech/vision change, seizure or severe sudden headache require urgent assessment.','active'),
('endocrinology_metabolism',50,'Endocrinology & Metabolism','specialty','Exact laboratory results, measurements, food/activity records, medicines and confirmed diagnoses.','Transparent time-series measurements.','Does not infer diagnosis or advise medicine change.','active'),
('gastroenterology',60,'Gastroenterology','specialty','Symptoms, food events, endoscopy/imaging/labs, medicines and confirmed diagnoses.','Dated digestive observations and reports.','Bleeding, severe persistent pain or dehydration require review.','active'),
('nephrology',70,'Nephrology','specialty','Renal labs, BP, imaging, fluid observations, medicines and confirmed diagnoses.','Dated kidney-related measurements with unit/specimen.','Does not stage disease or change fluid/medicine guidance.','active'),
('respiratory_medicine',80,'Respiratory Medicine','specialty','Symptoms, pulse-oximeter method/value, spirometry/imaging/labs, medicines and confirmed diagnoses.','Dated respiratory observations and reports.','Breathing difficulty or acute deterioration require emergency evaluation.','active'),
('dermatology_hair_eyes',90,'Dermatology, Hair & Eyes','specialty','Skin/hair/eye observations, consented photographs, screen exposure, examinations, labs and confirmed diagnoses.','Dated observable changes and source records.','Acute vision loss or severe eye pain requires urgent care.','active'),
('musculoskeletal_rehabilitation',100,'Musculoskeletal, Physiotherapy & Rehabilitation','rehabilitation','Pain/function, ROM method/value, strength/gait, imaging and session details.','Dated functional measures and rehabilitation sessions.','Does not diagnose injury or prescribe exercise without assessment.','active'),
('nutrition_food_medicine',110,'Nutrition & Food Medicine','lifestyle','Exact food identity, amount, preparation, time and approved nutrient mapping.','Dated food events and nutrient mass only for exact identity and portion.','No branded-food dependency, name-based mapping or therapeutic diet prescription.','active'),
('mental_health_sleep_behaviour',120,'Mental Health, Sleep & Behaviour','wellbeing','Optional self-reports, validated instrument version/score, sleep/activity, safety answers and shared clinician records.','Dated self-report and validated-score timeline.','Safety concerns override ordinary flows; no diagnosis from journal text.','active'),
('womens_reproductive_health',130,'Women''s & Reproductive Health','specialty','Cycle/reproductive observations, lab/imaging reports, medicines and confirmed records.','Private dated observations and reports under consent.','Pregnancy, heavy bleeding or severe pelvic pain require qualified care.','active'),
('dentistry_ent',140,'Dentistry & ENT','specialty','Dental/ENT reports, audiology, imaging/labs, medicines and symptom timeline.','Dated observations and documents.','Sudden hearing loss or airway compromise require urgent review.','active'),
('pharmacy_medicine_safety',150,'Pharmacy & Medicine Safety','safety','Medicine name, strength, form, route, schedule, label/prescription evidence and exact identity link.','Dated medicine record with verification state.','Never recommends starting, stopping or changing medicines.','active'),
('preventive_screening',160,'Preventive Health & Screening','prevention','Voluntary context, source screening report, test date and clinician recommendation.','Dated completed/pending screening record with provenance.','Does not generate universal schedules or diagnose.','active'),
('emergency_safety_events',170,'Emergency & Safety Events','safety','Time, event, reported symptoms, care location, outcome and source document.','Immutable dated safety event for escalation.','Not a substitute for emergency services.','active')
ON DUPLICATE KEY UPDATE display_order=VALUES(display_order),service_name=VALUES(service_name),service_group=VALUES(service_group),primary_inputs=VALUES(primary_inputs),timeline_output=VALUES(timeline_output),review_boundary=VALUES(review_boundary),status=VALUES(status);
INSERT INTO ilb_backend_object_registry(object_name,object_type,domain_key,canonical_role,frontend_access,lifecycle_status,replacement_object_name,decision_note,release_key) VALUES
('ilb_clinical_service_catalog','table','hospital','Governed clinical service catalogue.','read_contract','canonical',NULL,'Services define permitted inputs, dated outputs and safety boundaries; they do not create diagnoses.','ilb_backend_2026_07_24_complete'),
('v_ilb_clinical_service_catalog','view','hospital','Active clinical service read model.','read_contract','canonical',NULL,'Only active services are exposed to the hospital directory.','ilb_backend_2026_07_24_complete')
ON DUPLICATE KEY UPDATE object_type=VALUES(object_type),domain_key=VALUES(domain_key),canonical_role=VALUES(canonical_role),frontend_access=VALUES(frontend_access),lifecycle_status=VALUES(lifecycle_status),replacement_object_name=VALUES(replacement_object_name),decision_note=VALUES(decision_note),release_key=VALUES(release_key);
CREATE OR REPLACE VIEW v_ilb_clinical_service_catalog AS SELECT service_key,display_order,service_name,service_group,primary_inputs,timeline_output,review_boundary FROM ilb_clinical_service_catalog WHERE status='active' ORDER BY display_order;
COMMIT;