INSERT INTO ilb_psoriasis_cell(cell_id,cell_type,location_text,role_class,psoriasis_role,key_receptors_markers,key_outputs,ilmb_note,source_url) VALUES
('CELL-001','Keratinocyte','Epidermis','Structural/immune effector','Responds strongly to IL-17/TNF/IL-22; produces chemokines, antimicrobial proteins and cytokines; proliferation/differentiation become abnormal.','IL-17RA/RC, TNFR, IL-36R','IL-17A/F, TNF, IL-22, IL-36','Core disease-expression cell','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-002','Myeloid dendritic cell','Dermis/skin','Antigen-presenting / cytokine source','Produces IL-23 and other inflammatory mediators that support type-17 responses.','IL-23 pathway','IL-23, TNF','Major bridge from innate to adaptive immunity','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-003','Plasmacytoid dendritic cell','Early lesion dermis','Innate immune','Can produce type I interferon in early disease after nucleic-acid/LL37 sensing.','TLR7/9','IFN-alpha','More relevant to initiation than chronic maintenance','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-004','Th17 cell','Skin/blood','Adaptive T cell','Produces IL-17A/F and IL-22; supported by IL-23.','IL-23R','IL-17A/F, IL-22','Canonical pathogenic population','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-005','Tc17 / CD8 T cell','Epidermis/skin','Adaptive T cell','Produces IL-17-family cytokines; epidermal localization can be important.','IL-23R','IL-17A/F','Contributes to local disease','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-006','Tissue-resident memory T cell','Resolved/active skin','Memory T cell','Persists in previously affected skin and can rapidly reactivate inflammatory programs.','CD69, CD103 context-dependent','IL-17, IL-22','Key relapse/cure-research target','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-007','Neutrophil','Epidermis/pustules','Innate effector','Forms Munro microabscesses/Kogoj pustules; dominant in pustular psoriasis.','Chemokine receptors','Proteases, ROS','Central to pustular phenotypes','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-008','Macrophage','Dermis','Innate immune','Produces inflammatory cytokines and shapes tissue inflammation.','Multiple','TNF, IL-1 family','Supporting role','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-009','Mast cell','Dermis','Innate/neuroimmune','Can release mediators and interact with nerves.','NK1R and others','Histamine, proteases, cytokines','Neuroimmune contributor','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-010','Sensory neuron','Cutaneous nerves','Neuroimmune','Releases neuropeptides and receives inflammatory input.','TRPV1/TRPA1, neuropeptide receptors','CGRP, Substance P','Links itch/pain/stress and inflammation','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-011','Fibroblast','Dermis','Stromal','Can retain inflammatory transcriptional states and contribute chemokines.','Multiple','ECM/chemokines','Potential tissue-memory contributor','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('CELL-012','Endothelial cell','Dermal microvasculature','Vascular','Angiogenesis and leukocyte trafficking are increased in plaques.','Adhesion molecules','VEGF-responsive','Supports inflammatory cell recruitment','https://pubmed.ncbi.nlm.nih.gov/33812489/')
ON DUPLICATE KEY UPDATE cell_type=VALUES(cell_type),psoriasis_role=VALUES(psoriasis_role),ilmb_note=VALUES(ilmb_note),source_url=VALUES(source_url);

INSERT INTO ilb_psoriasis_bioentity(entity_id,entity_name,entity_type,symbol_text,main_source_cell,target_or_receptor,role_text,expected_state,evidence_class,source_url) VALUES
('MOL-001','IL-23','Cytokine','IL23A/IL12B complex','Dendritic cells','IL-23R on type-17 cells','Maintains pathogenic type-17 responses','↑ active disease','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-002','IL-17A','Cytokine','IL17A','Th17/Tc17/TRM and others','IL-17RA/RC','Keratinocyte inflammatory program; chemokines and antimicrobial proteins','↑ active disease','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-003','IL-17F','Cytokine','IL17F','Type-17 cells','IL-17RA/RC','Overlaps IL-17A; contributes to inflammation','↑ active disease','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-004','IL-22','Cytokine','IL22','Th17/Th22 and others','IL-22R','Keratinocyte proliferation/differentiation effects','↑ active disease','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-005','TNF-alpha','Cytokine','TNF','Multiple immune cells','TNFR1/2','Amplifies inflammation and synergizes with IL-17','↑ active disease','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-006','IL-36 alpha/beta/gamma','Cytokine family','IL36A/B/G','Keratinocytes/immune cells','IL-36R','Autocrine inflammatory amplification; neutrophil chemokines','↑ especially GPP','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-007','IL-36 receptor antagonist','Regulator','IL36RN','Keratinocytes/others','IL-36R antagonism','Restrains IL-36 signaling','Loss-of-function predisposes GPP','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-008','LL37','Antimicrobial peptide','CAMP','Keratinocytes/neutrophils','Nucleic-acid complexes sensed by innate receptors','Can facilitate innate immune activation','↑ lesions','Supported','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-009','CCL20','Chemokine','CCL20','Keratinocytes','CCR6','Recruits CCR6+ type-17 cells','↑ lesions','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-010','CXCL1/CXCL8','Chemokines','CXCL1/CXCL8','Keratinocytes/immune cells','CXCR1/2 context','Neutrophil recruitment','↑ pustular/active','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-011','S100A7/A8/A9','Antimicrobial/alarm proteins','S100 genes','Keratinocytes','Multiple','Inflammatory amplification/biomarker-like lesion proteins','↑ lesions','Established','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-012','CGRP','Neuropeptide','CALCA peptide','Sensory neurons','CGRP receptors','Neuroimmune modulation; experimental links to IL-23 axis','May ↑ local inflammation','Mechanistic/experimental','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-013','Substance P','Neuropeptide','TAC1 peptide','Sensory neurons','NK1R','Neuroimmune signaling, itch/pain/inflammation','May ↑ local inflammation','Supported/experimental','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-014','NGF','Growth factor','NGF','Keratinocytes/immune/neuronal context','TrkA','Nerve growth/sensitization and neuroimmune crosstalk','May ↑ neural drive','Supported','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('MOL-015','VEGF','Growth factor','VEGFA','Keratinocytes/immune/stromal','VEGFR','Angiogenesis and vascular changes','↑ plaques','Supported','https://pubmed.ncbi.nlm.nih.gov/33812489/'),
('GEN-001','HLA-C*06:02','Genetic risk allele','HLA-C','Inherited','MHC class I','Strong plaque-psoriasis susceptibility association','Risk allele','Established','https://pubmed.ncbi.nlm.nih.gov/33955502/'),
('GEN-002','IL36RN','Gene','IL36RN','Inherited','IL-36 pathway','Loss-of-function variants strongly linked to GPP subset','Risk variant','Established','https://pubmed.ncbi.nlm.nih.gov/33955502/'),
('GEN-003','CARD14','Gene','CARD14','Inherited/keratinocyte signaling','NF-kB pathway','Variants can predispose plaque/pustular phenotypes','Risk variant','Established','https://pubmed.ncbi.nlm.nih.gov/33955502/'),
('GEN-004','AP1S3','Gene','AP1S3','Inherited','Vesicle/autophagy biology','Risk variants in pustular psoriasis subset','Risk variant','Established','https://pubmed.ncbi.nlm.nih.gov/33955502/'),
('GEN-005','MPO','Gene','MPO','Inherited/neutrophil','Myeloperoxidase','Recessive variants reported in GPP','Risk variant','Established','https://pubmed.ncbi.nlm.nih.gov/33955502/')
ON DUPLICATE KEY UPDATE entity_name=VALUES(entity_name),role_text=VALUES(role_text),evidence_class=VALUES(evidence_class),source_url=VALUES(source_url);
