<?php
declare(strict_types=1);
$p=new PDO('mysql:host=127.0.0.1;dbname=ehr_test;charset=utf8mb4','root','ci-only-password',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::MYSQL_ATTR_MULTI_STATEMENTS=>true]);
function runSql(PDO $p,string $path): void {$s=$p->query(file_get_contents($path));do{if($s->columnCount())$s->fetchAll();}while($s->nextRowset());}
function check(bool $ok,string $msg):void{if(!$ok)throw new RuntimeException($msg);}
runSql($p,__DIR__.'/fixtures/energy-healing.sql');
foreach([1,2] as $pass)foreach(['energy_healing_department.sql','energy_healing_loinc_links.sql','energy_healing_pranic_entry.sql','energy_healing_magnified_entry.sql','energy_healing_process_maps.sql','energy_healing_catalogue.sql','energy_healing_convergence.sql','energy_healing_process_reviews.sql','energy_healing_literature.sql','energy_healing_research_followup.sql','energy_healing_candidate_extraction.sql'] as $f)runSql($p,__DIR__.'/../backend/'.$f);
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_practice')->fetchColumn()===50,'Rerun duplicated practices');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_section')->fetchColumn()===16,'Rerun duplicated sections');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_evidence_review')->fetchColumn()===25,'Rerun duplicated reviews');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_claim WHERE practice_code='MAGNIFIED_HEALING'")->fetchColumn()===5,'Magnified claims missing or duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_protocol WHERE practice_code='MAGNIFIED_HEALING' AND research_status='DRAFT'")->fetchColumn()===3,'Magnified draft protocols missing');
$p->exec("INSERT INTO ilb_ehr_session(session_key,practice_code,subject_key,started_at,delivery_mode,status) VALUES('fixture','PRANIC_HEALING','test-subject','2026-01-01','PROXIMITY','COMPLETED')");
$id=(int)$p->lastInsertId();$p->exec("INSERT INTO ilb_ehr_session_result_link VALUES($id,1,'BASELINE','Synthetic','test-login',CURRENT_TIMESTAMP),($id,2,'BASELINE','Synthetic','test-login',CURRENT_TIMESTAMP)");
check((int)$p->query('SELECT COUNT(*) FROM v_ilb_ehr_session_loinc_result')->fetchColumn()===1,'Cross-subject result visible');
check($p->query('SELECT reported_value_text FROM v_ilb_ehr_session_loinc_result')->fetchColumn()==='positive','Qualitative result lost');
$p->exec("UPDATE ilb_test_atlas_loinc_crosswalk SET mapping_status='REJECTED'");
check((int)$p->query('SELECT COUNT(*) FROM v_ilb_ehr_session_loinc_result')->fetchColumn()===0,'Revoked mapping visible');
$p->exec("UPDATE ilb_test_atlas_loinc_crosswalk SET mapping_status='APPROVED'; UPDATE ilb_ehr_session SET status='CANCELLED'");
check((int)$p->query('SELECT COUNT(*) FROM v_ilb_ehr_session_loinc_result')->fetchColumn()===0,'Cancelled session visible');
$p->exec("UPDATE ilb_ehr_session SET status='COMPLETED'; UPDATE ilb_subject_test_result_ledger SET entry_status='VOID' WHERE result_id=1");
check((int)$p->query('SELECT COUNT(*) FROM v_ilb_ehr_session_loinc_result')->fetchColumn()===0,'Void result visible');
$p->exec("UPDATE ilb_subject_test_result_ledger SET entry_status='ACTIVE' WHERE result_id=1; DELETE FROM ilb_ehr_session_result_link; DELETE FROM ilb_ehr_session;");
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_process_map')->fetchColumn()===2,'Process maps duplicated');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_process_connection')->fetchColumn()===8,'Process connections duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_process_connection WHERE modality_causal_status='SUPPORTED' OR sequence_position IS NOT NULL")->fetchColumn()===0,'Unsupported process validation or sequence inserted');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_catalogue')->fetchColumn()===50,'Catalogue missing or duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_catalogue WHERE record_kind='BRANCH' AND parent_practice_code IS NULL")->fetchColumn()===0,'Branch parent missing');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_practice WHERE publication_status='PUBLISHED'")->fetchColumn()===2,'Catalogue published unreviewed entries');
$p->exec("INSERT INTO ilb_ehr_process_map VALUES('TEST_DRAFT','REIKI','Synthetic hidden outcome','SOURCE_GAP','UNKNOWN',NULL,'Synthetic fixture','Synthetic private draft')");
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_convergence_feature')->fetchColumn()===9,'Convergence themes duplicated');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_convergence_observation')->fetchColumn()===34,'Convergence observations duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_convergence_observation WHERE finding_status='CLINICALLY_VALIDATED'")->fetchColumn()===0,'Teaching similarity presented as clinical validation');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_convergence_observation WHERE component_status='OPTIONAL' AND practice_code='THERAPEUTIC_TOUCH'")->fetchColumn()===1,'Optional breathing lost');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_process_review')->fetchColumn()===50,'Process reviews missing or duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_process_review WHERE clinical_review_status<>'NOT_REVIEWED'")->fetchColumn()===0,'Teaching extraction promoted to clinical evidence');
check($p->query("SELECT delivery_scope FROM ilb_ehr_process_review WHERE practice_code='CORE_SHAMANISM'")->fetchColumn()==='OTHER','Recipient-only course misrepresented');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_search_audit')->fetchColumn()===50,'Search audit missing or duplicated');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_study_scope')->fetchColumn()===24,'Study scopes missing or duplicated');
check($p->query("SELECT population_scope FROM ilb_ehr_study_scope WHERE claim_key='ABSTRACT_32284695'")->fetchColumn()==='ANIMAL','Animal finding misclassified');
check($p->query("SELECT notice_status FROM ilb_ehr_study_scope WHERE claim_key='ABSTRACT_32649851'")->fetchColumn()==='CHECKED','Correction notice lost');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_study_scope WHERE material_reviewed='FULL_TEXT'")->fetchColumn()===7,'Full-text reviews missing or abstract promoted');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_candidate_screen')->fetchColumn()===290,'Candidate screening register duplicated or missing');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_candidate_screen WHERE screening_status='AWAITING_SCREENING'")->fetchColumn()===0,'Old title-screening queue not resolved');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_screen_assessment')->fetchColumn()===290,'Screening assessments missing');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_notice_review')->fetchColumn()===2,'Notice reviews missing');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_database_search WHERE retrieval_status='OK'")->fetchColumn()===50,'Expanded database searches missing');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_research_gate WHERE research_complete=1')->fetchColumn()===0,'Open research falsely completed');
check($p->query("SELECT study_design FROM ilb_ehr_evidence_review e JOIN ilb_ehr_claim c ON c.claim_id=e.claim_id WHERE c.claim_key='ABSTRACT_24327820'")->fetchColumn()==='Nonrandomized controlled study; rotating recruitment-order assignment','Allocation misclassified');
check((int)$p->query('SELECT COUNT(*) FROM ilb_ehr_candidate_extraction')->fetchColumn()===100,'Primary-record extractions missing or duplicated');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_candidate_extraction WHERE material_reviewed='NO_ABSTRACT'")->fetchColumn()===1,'Unavailable abstract falsely extracted');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_candidate_screen WHERE screening_status='ABSTRACT_EXTRACTED_FULL_REVIEW_PENDING'")->fetchColumn()===97,'Full review pending status lost');
check((int)$p->query("SELECT COUNT(*) FROM ilb_ehr_candidate_screen WHERE screening_status='TITLE_ELIGIBLE_EXTRACTION_PENDING'")->fetchColumn()===0,'Earlier extraction queue not processed');
check(str_contains($p->query("SELECT interpretation_text FROM ilb_ehr_candidate_extraction WHERE pmid='36121655'")->fetchColumn(),'p=.13 nonsignificant'),'Primary null outcome lost');
check(str_contains($p->query("SELECT interpretation_text FROM ilb_ehr_candidate_extraction WHERE pmid='15102336'")->fetchColumn(),'failed replication'),'Replication failure lost');
require __DIR__.'/../ops/audit-energy-healing.php';
$audit=auditEnergyHealing($p);
check($audit['integrity_status']==='PASS','Coverage integrity audit failed');
check($audit['catalogue_records']===50,'Coverage audit lost catalogue records');
check($audit['records_with_open_research_gaps']===50,'Incomplete research incorrectly marked complete');
$p->exec("UPDATE ilb_ehr_catalogue SET parent_practice_code=NULL WHERE practice_code='JIKIDEN_REIKI'");
check(auditEnergyHealing($p)['integrity_status']==='FAIL','Audit missed broken branch identity');
$p->exec("UPDATE ilb_ehr_catalogue SET parent_practice_code='REIKI' WHERE practice_code='JIKIDEN_REIKI'");
echo "SQL integration and research coverage audit checks passed\n";
