<?php
declare(strict_types=1);
header('X-Robots-Tag: noindex,nofollow,noarchive');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
$error='';$enteredId='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $enteredId=strtolower(trim((string)($_POST['user_id']??'')));$password=(string)($_POST['password']??'');
 if(!preg_match('/^[a-z0-9][a-z0-9_-]{1,63}$/',$enteredId)){$error='Enter the Patient ID exactly as the hospital gave it to you.';}
 elseif($password===''){$error='Enter your password.';}
 else{$target=__DIR__.DIRECTORY_SEPARATOR.$enteredId.'.php';
  if(!is_file($target)||in_array($enteredId,['index','access','new','api','lib','config','_guard','hospital-review','hospital-review-api','test-results','test-results-api'],true)){$error='That Patient ID is not activated. Check the ID or use the mobile + PIN option if that is how your record was created.';}
  else{require $target;exit;}
 }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#fff9fb"><title>Patient Access · I Love My Body</title><style>
:root{--bg:#fff9fb;--card:#fff;--ink:#281a23;--muted:#756873;--line:#eadde4;--rose:#b74772;--peach:#efb492;--soft:#fff3f7}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(180deg,#fff9fb,#f8f3f6);color:var(--ink);font-family:system-ui,-apple-system,Segoe UI,sans-serif}.wrap{width:min(1050px,calc(100% - 28px));margin:auto;padding:28px 0 70px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.brand{font-weight:800}.brand small{display:block;color:var(--muted);font-size:10px;letter-spacing:.12em}.back{color:var(--rose);text-decoration:none;font-size:13px}.hero{padding:52px 0 26px;max-width:800px}.ey{color:var(--rose);font-size:10px;font-weight:800;letter-spacing:.14em}.hero h1{font:500 clamp(38px,6vw,66px)/1.02 Georgia,serif;margin:9px 0 12px}.hero p{color:var(--muted);line-height:1.7}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.card{padding:26px;border:1px solid var(--line);border-radius:20px;background:white;box-shadow:0 12px 36px rgba(75,43,58,.05)}.card h2{font:500 29px Georgia,serif;margin:7px 0}.card p{color:var(--muted);line-height:1.6}.field{display:block;margin:14px 0 6px;color:var(--muted);font-size:12px}input{width:100%;padding:12px;border:1px solid var(--line);border-radius:10px;background:white;color:var(--ink);font:inherit}.primary{width:100%;margin-top:16px;padding:12px;border:0;border-radius:10px;background:var(--peach);color:#4b2c38;font-weight:800;cursor:pointer}.alt{display:block;margin-top:15px;color:var(--rose);text-decoration:none;font-weight:700}.note{margin-top:16px;padding:13px;border-left:3px solid #dfa8bc;background:var(--soft);color:var(--muted);font-size:12px;line-height:1.55}.error{color:#b33b45;margin-top:10px;font-size:12px}.first{display:inline-flex;margin-top:10px;padding:10px 14px;border:1px solid var(--line);border-radius:999px;color:var(--ink);text-decoration:none;background:white;font-size:12px}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column-reverse}.hero{padding-top:34px}}
</style></head><body><main class="wrap"><div class="top"><a class="back" href="/hospital.html">← Back to hospital</a><div class="brand">I Love My Body<small>PRIVATE PATIENT ACCESS</small></div></div><section class="hero"><div class="ey">RETURNING PATIENT</div><h1>Open the same journey you started before.</h1><p>Your reports, prescription audit, treatment comparison, measurements and hospital review belong in one private space.</p><a class="first" href="/app/new.php">First visit? Preview the whole journey without login →</a></section><div class="grid"><section class="card"><div class="ey">PATIENT ID + PASSWORD</div><h2>Hospital-issued access</h2><p>Use this when the hospital has specifically issued you a Patient ID and password.</p><form method="post"><label class="field">Patient ID</label><input name="user_id" autocomplete="username" autocapitalize="none" spellcheck="false" value="<?=htmlspecialchars($enteredId,ENT_QUOTES,'UTF-8')?>" required><label class="field">Password</label><input name="password" type="password" autocomplete="current-password" required><button class="primary">Open my patient journey →</button><?php if($error):?><div class="error" role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?></form></section><section class="card"><div class="ey">MOBILE + 6-DIGIT PIN</div><h2>Existing My Happy Space access</h2><p>If your record was created with your mobile number and a 6-digit PIN, continue through the main private patient workspace.</p><a class="alt" href="/app/">Open mobile + PIN sign-in →</a><div class="note"><b>Nothing changes your prescription automatically.</b><br>The private workspace records reports, medicines, measurements and your response. Prescription comparisons explain benefit, burden and ILMB targets; they do not tell you to stop a prescribed medicine.</div></section></div></main></body></html>