<?php
declare(strict_types=1);
require __DIR__ . '/_guard.php';
require __DIR__ . '/lib.php';
start_private_session();
if (empty($_SESSION['ilb_reviewer'])) { header('Location: admin.php'); exit; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Body Need Master — ILMB Console</title><style>
:root{--bg:#f7f8fa;--card:#fff;--ink:#111827;--muted:#6b7280;--line:#d1d5db;--accent:#2563eb;--warn:#b45309}.wrap{max-width:1500px;margin:auto;padding:18px}*{box-sizing:border-box}body{margin:0;background:var(--bg);font:14px/1.4 Inter,Arial,sans-serif;color:var(--ink)}header{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}header h1{margin:0;font-size:22px;font-weight:600}nav a{margin-left:12px;color:var(--ink)}.stats{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:10px}.card,.panel{background:var(--card);border:1px solid var(--line);border-radius:12px}.card{padding:12px}.card b{display:block;font-size:24px}.card span,.muted{color:var(--muted)}.panel{margin-top:12px;padding:12px}.tabs{display:flex;gap:7px;flex-wrap:wrap}.tabs button{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 10px;cursor:pointer}.tabs button.active{background:var(--ink);color:#fff}.toolbar{display:flex;justify-content:space-between;gap:10px;margin:10px 0}.toolbar input{min-width:280px;padding:8px;border:1px solid var(--line);border-radius:8px}.table{overflow:auto;max-height:66vh;border:1px solid var(--line);border-radius:8px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:7px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top;white-space:nowrap}th{position:sticky;top:0;background:#f3f4f6;z-index:1}.bad{color:#b91c1c}.good{color:#047857}.warn{color:var(--warn)}code{font-family:ui-monospace,Consolas,monospace}@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}header{align-items:flex-start}.toolbar{flex-direction:column}.toolbar input{min-width:0;width:100%}}</style></head><body><main class="wrap"><header><div><div class="muted">I LOVE MY BODY · PRIVATE CONSOLE</div><h1>Body Need / Formula Master</h1></div><nav><a href="admin.php">Case review</a><a href="../body-needs.html" target="_blank">Public page</a></nav></header>
<section class="stats" id="stats"></section>
<section class="panel"><div class="tabs"><button data-view="parameters" class="active">Parameters</button><button data-view="formulas">Formulas</button><button data-view="inputs">Formula Inputs</button><button data-view="identifier-gaps">LOINC / ChEBI gaps</button><button data-view="duplicates">Duplicates</button></div><div class="toolbar"><input id="q" placeholder="Filter current table"><span id="status" class="muted">Loading…</span></div><div class="table"><table><thead id="thead"></thead><tbody id="tbody"></tbody></table></div></section></main><script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rows=[];
function renderTable(data){rows=data||[];const q=document.getElementById('q').value.toLowerCase();const filtered=rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q));const keys=[...new Set(filtered.slice(0,200).flatMap(Object.keys))];document.getElementById('thead').innerHTML='<tr>'+keys.map(k=>`<th>${esc(k)}</th>`).join('')+'</tr>';document.getElementById('tbody').innerHTML=filtered.map(r=>'<tr>'+keys.map(k=>`<td>${typeof r[k]==='object'?esc(JSON.stringify(r[k])):esc(r[k])}</td>`).join('')+'</tr>').join('');document.getElementById('status').textContent=`${filtered.length} of ${rows.length}`}
async function loadSummary(){const j=await fetch('body-need-api.php?view=summary',{cache:'no-store'}).then(r=>r.json());const s=j.summary||{};const items=[['Parameters',s.parameters],['Identifiers',s.identifiers],['Formulas',s.formulas],['Inputs',s.formula_inputs],['Open duplicates',(s.parameter_duplicates||0)+(s.formula_duplicates||0)],['Computed runs',s.computed_runs]];document.getElementById('stats').innerHTML=items.map(([a,b])=>`<article class="card"><b>${esc(b??0)}</b><span>${esc(a)}</span></article>`).join('')}
async function load(view){document.getElementById('status').textContent='Loading…';const j=await fetch('body-need-api.php?view='+encodeURIComponent(view),{cache:'no-store'}).then(r=>r.json());let d=[];if(view==='duplicates')d=[...(j.parameter_duplicates||[]).map(x=>({...x,duplicate_type:'PARAMETER'})),...(j.formula_duplicates||[]).map(x=>({...x,duplicate_type:'FORMULA'}))];else d=j[view.replace('-','_')]||j.gaps||[];renderTable(d)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.view)});document.getElementById('q').oninput=()=>renderTable(rows);loadSummary();load('parameters');setInterval(loadSummary,60000);
</script></body></html>