<?php
declare(strict_types=1);
header('Cache-Control: no-store');
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>Stroke / Vascular Risk Default Plan · I Love My Body</title><link rel="stylesheet" href="/assets/ilmb-brand.css?v=6"><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#000;font:14px/1.45 Arial,sans-serif}.wrap{max-width:1600px;margin:auto;padding:16px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.brand{font-size:22px;font-weight:900}.brand small{display:block;font-size:9px;letter-spacing:.14em}.back{border:1px solid #000;border-radius:999px;padding:8px 12px;color:#000;text-decoration:none;font-weight:800}.hero{margin:14px 0;border:3px solid #ff008c;border-radius:16px;padding:16px}.ey{font-size:9px;font-weight:900;color:#ff008c;letter-spacing:.14em;text-transform:uppercase}.hero h1{font-size:34px;line-height:1.05;margin:5px 0}.hero p{margin:5px 0;color:rgba(0,0,0,.65);max-width:1100px}.rule{margin-top:10px;background:#000;color:#fff;border-radius:10px;padding:10px 12px;font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{border:1px solid #000;border-radius:14px;padding:14px;background:#fff}.card h2{margin:3px 0 8px;font-size:22px}.targets{width:100%;border-collapse:collapse}.targets th,.targets td{border:1px solid #000;padding:9px;vertical-align:top;text-align:left}.targets th{background:#000;color:#fff;font-size:10px;text-transform:uppercase}.targets td:first-child{font-weight:900}.pink{color:#ff008c}.week{display:grid;grid-template-columns:repeat(7,minmax(220px,1fr));gap:8px;overflow-x:auto;padding-bottom:6px}.day{border:1px solid #000;border-radius:12px;padding:10px;min-width:220px}.day h3{margin:0 0 7px;font-size:17px}.meal{border-top:1px solid rgba(0,0,0,.18);padding:7px 0}.meal b{display:block;font-size:9px;text-transform:uppercase;color:#ff008c;letter-spacing:.08em}.meal p{margin:2px 0;font-size:11px}.recipes{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.recipe{border:1px solid #000;border-radius:10px;padding:10px}.recipe h3{margin:0 0 5px;font-size:14px}.recipe ul{margin:4px 0;padding-left:17px;font-size:11px}.recipe p{margin:5px 0 0;font-size:11px}.life{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.life article{border:1px solid #000;border-radius:10px;padding:10px}.life b{display:block;color:#ff008c;margin-bottom:4px}.life p{margin:0;font-size:11px}.gate{border-left:5px solid #ff008c;padding:10px 12px;margin-top:10px;background:#fff}.gate b{display:block;margin-bottom:4px}.small{font-size:10px;color:rgba(0,0,0,.65)}@media(max-width:1000px){.grid,.recipes,.life{grid-template-columns:1fr 1fr}}@media(max-width:650px){.wrap{padding:10px}.top{align-items:flex-start;flex-direction:column}.grid,.recipes,.life{grid-template-columns:1fr}.hero h1{font-size:28px}}
</style></head><body><main class="wrap"><header class="top"><div class="brand">I Love My Body<small>DISEASE DEFAULT PLAN · STROKE / VASCULAR RISK</small></div><a class="back" href="/hospital.html">Hospital</a></header>
<section class="hero"><div class="ey">GENERIC ADULT DEFAULT · VERSION 1</div><h1>A complete one-week starting plan before personalisation</h1><p>This is the disease default for a generic adult with prior ischemic stroke / vascular risk. It is not yet a named patient's plan. Patient measurements, medicines, kidney/liver function, potassium, allergies, body size, activity and swallowing/function status override this default.</p><div class="rule">DISEASE NEED → EXACT ACTION → DOSE / GRAMS / MINUTES → SAME OUTPUT MEASURED → PERSONALISE FROM REAL DATA</div></section>
<section class="card"><div class="ey">PHARMACY = ILMB</div><h2>What the default plan is trying to change</h2><table class="targets"><thead><tr><th>Target</th><th>Pharma path</th><th>ILMB path</th><th>Default action</th><th>Same output</th></tr></thead><tbody>
<tr><td>BP / vascular resistance</td><td>Antihypertensive medicine lowers pressure by its drug mechanism.</td><td>Lower sodium load + regular aerobic work + better autonomic/sleep state.</td><td><b>30 min moderate aerobic work × 5 days/week</b>, RPE about 3–4/10; resistance work <b>2 days/week</b>; low-salt food pattern.</td><td>SBP / DBP / resting pulse</td></tr>
<tr><td>Heart rate / cardiac load</td><td>Beta-blocker route lowers HR/workload when prescribed.</td><td>Conditioning + autonomic balance + sleep.</td><td>Use the same aerobic programme. If a beta-blocker is present, use <b>RPE and symptoms</b>, not a generic target-HR formula.</td><td>Resting HR / BP / effort tolerance</td></tr>
<tr><td>Triglyceride-rich particles</td><td>Fibrate/statin pathways reduce TG/VLDL burden.</td><td>Lower high-glycemic/refined substrate + increase muscle use + remove alcohol excess.</td><td><b>150 min/week</b> aerobic + resistance <b>2–3×/week</b>; no sugar-sweetened drinks; no routine alcohol in the default programme; measured food portions.</td><td>Fasting TG · LOINC 2571-8</td></tr>
<tr><td>LDL / non-HDL / apoB</td><td>Statin route reduces HMGCR pathway and increases LDL clearance.</td><td>Soluble fibre + plant sterol route + food-fat quality + activity.</td><td><b>Psyllium 10.2 g/day</b> with adequate water; <b>plant sterols/stanols 2 g/day</b> from an identified food/product; exercise as above.</td><td>LDL-C / non-HDL-C / apoB</td></tr>
<tr><td>Recurrent thrombotic risk</td><td>Antiplatelet therapy reduces platelet-driven clotting where indicated.</td><td>No proven direct food/exercise substitute for P2Y12 or aspirin COX-1 protection.</td><td><b>Do not replace antiplatelet medicines.</b> Run BP, lipid, activity, smoking/alcohol, sleep and metabolic-risk modules in parallel.</td><td>Clinical recurrence + clinician-selected platelet testing if useful</td></tr>
<tr><td>Motor recovery if deficit exists</td><td>No routine medicine rebuilds a motor network.</td><td>Repeated task practice + strength + gait + selected rehab.</td><td>Train the exact impaired task <b>daily</b>; walking/strength block <b>5 days/week as tolerated</b>; add FES/CIMT/mirror only when indicated.</td><td>Grip / 10-m walk / sit-to-stand / dexterity</td></tr>
</tbody></table></section>
<section class="card"><div class="ey">7-DAY FOOD PLAN</div><h2>Exact default meals and quantities</h2><div class="week">
<article class="day"><h3>Day 1</h3><div class="meal"><b>Breakfast</b><p>Oats 50 g + low-fat curd 150 g + apple 120 g + chia 10 g.</p></div><div class="meal"><b>Mid-morning</b><p>Guava 120 g.</p></div><div class="meal"><b>Lunch</b><p>2 rotis from whole-wheat flour 60 g + moong dal 35 g dry + lauki 200 g + salad 150 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Roasted chana 25 g.</p></div><div class="meal"><b>Dinner</b><p>Tofu 120 g OR fish 120 g + mixed vegetables 250 g + 1 roti from flour 30 g + oil 5 g.</p></div></article>
<article class="day"><h3>Day 2</h3><div class="meal"><b>Breakfast</b><p>Besan 60 g chilla + mixed vegetables 100 g + curd 100 g.</p></div><div class="meal"><b>Mid-morning</b><p>Pear 120 g.</p></div><div class="meal"><b>Lunch</b><p>Brown rice 45 g raw + rajma 35 g dry + beans/cabbage 200 g + salad 150 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Unsalted almonds 15 g.</p></div><div class="meal"><b>Dinner</b><p>Vegetable soup 300 g + paneer low-fat 100 g OR chicken 120 g + 1 roti flour 30 g.</p></div></article>
<article class="day"><h3>Day 3</h3><div class="meal"><b>Breakfast</b><p>Poha 50 g dry + peas/vegetables 120 g + peanuts 10 g.</p></div><div class="meal"><b>Mid-morning</b><p>Orange 130 g.</p></div><div class="meal"><b>Lunch</b><p>2 rotis flour 60 g + masoor dal 35 g dry + bhindi 200 g + salad 150 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Buttermilk 200 ml, unsalted.</p></div><div class="meal"><b>Dinner</b><p>Fish 120 g OR tofu 120 g + vegetables 250 g + dalia 35 g dry.</p></div></article>
<article class="day"><h3>Day 4</h3><div class="meal"><b>Breakfast</b><p>Oats 50 g + curd 150 g + pear 120 g + ground flax 10 g.</p></div><div class="meal"><b>Mid-morning</b><p>Apple 120 g.</p></div><div class="meal"><b>Lunch</b><p>Dalia 50 g dry + chana dal 30 g dry + mixed vegetables 250 g + curd 100 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Roasted makhana 20 g.</p></div><div class="meal"><b>Dinner</b><p>2 small rotis flour 60 g + mixed vegetable 250 g + tofu/paneer/chicken 100–120 g.</p></div></article>
<article class="day"><h3>Day 5</h3><div class="meal"><b>Breakfast</b><p>Moong dal 60 g dry chilla + vegetables 100 g + mint/coriander chutney without added salt.</p></div><div class="meal"><b>Mid-morning</b><p>Guava 120 g.</p></div><div class="meal"><b>Lunch</b><p>Brown rice 45 g raw + tur dal 35 g dry + lauki/tori 200 g + salad 150 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Low-fat curd 150 g.</p></div><div class="meal"><b>Dinner</b><p>Chicken/fish/tofu 120 g + vegetables 250 g + 1 roti flour 30 g.</p></div></article>
<article class="day"><h3>Day 6</h3><div class="meal"><b>Breakfast</b><p>Vegetable upma: rava/dalia 50 g + vegetables 120 g + oil 5 g.</p></div><div class="meal"><b>Mid-morning</b><p>Pear 120 g.</p></div><div class="meal"><b>Lunch</b><p>2 rotis flour 60 g + chana 35 g dry + mixed vegetables 200 g + salad 150 g.</p></div><div class="meal"><b>Evening</b><p>Unsalted walnuts 15 g.</p></div><div class="meal"><b>Dinner</b><p>Soup 300 g + tofu/paneer/fish/chicken 120 g + dalia 35 g dry.</p></div></article>
<article class="day"><h3>Day 7</h3><div class="meal"><b>Breakfast</b><p>Oats 50 g OR besan 60 g chilla + curd 100 g + fruit 120 g.</p></div><div class="meal"><b>Mid-morning</b><p>One fruit portion 120–150 g.</p></div><div class="meal"><b>Lunch</b><p>2 rotis flour 60 g + dal 35 g dry + vegetables 250 g + salad 150 g + oil 5 g.</p></div><div class="meal"><b>Evening</b><p>Roasted chana 25 g.</p></div><div class="meal"><b>Dinner</b><p>Protein 120 g + vegetables 250 g + 1 roti flour 30 g. Finish dinner at least 2–3 h before sleep.</p></div></article>
</div><div class="gate"><b>Daily default add-on</b>Psyllium / isabgol total <b>10.2 g/day</b>, usually split into two doses with adequate water. Plant sterols/stanols <b>2 g/day</b> only from a product/food whose actual sterol amount is known. These are LDL-focused tools, not substitutes for antiplatelet medicines.</div></section>
<section class="card"><div class="ey">RECIPES</div><h2>Simple recipe instructions</h2><div class="recipes">
<article class="recipe"><h3>Moong chilla</h3><ul><li>Dry moong 60 g, soaked</li><li>Onion/tomato/capsicum 100 g total</li><li>Oil 5 g</li><li>Spices, lemon, herbs; no extra table salt</li></ul><p>Blend soaked moong with water, fold in vegetables, cook as 2–3 thin chillas using the measured oil.</p></article>
<article class="recipe"><h3>Dal + vegetable bowl</h3><ul><li>Any listed dal 35 g dry</li><li>Vegetables 200–250 g</li><li>Oil 5 g</li><li>Ginger, cumin, turmeric, coriander</li></ul><p>Pressure-cook dal; cook vegetables separately or together. Keep oil measured. Do not add packaged masala/soup powders as routine sodium sources.</p></article>
<article class="recipe"><h3>Protein + vegetables</h3><ul><li>Fish/chicken/tofu 120 g OR low-fat paneer 100 g</li><li>Mixed vegetables 250 g</li><li>Oil 5 g</li><li>Lemon/herbs/spices</li></ul><p>Grill, bake or pan-cook with the measured oil. Avoid deep frying and sugary sauces.</p></article>
<article class="recipe"><h3>Oats bowl</h3><ul><li>Oats 50 g</li><li>Low-fat curd 150 g</li><li>Fruit 120 g</li><li>Chia or ground flax 10 g</li></ul><p>Use as a cold bowl or cook oats in water and add curd after cooling. No sugar or honey in the default plan.</p></article>
<article class="recipe"><h3>Dalia bowl</h3><ul><li>Dalia 50 g dry</li><li>Vegetables 200–250 g</li><li>Dal 30 g dry when used as full meal</li><li>Oil 5 g</li></ul><p>Cook together until soft. Use herbs, lemon and spices for flavour instead of extra salt.</p></article>
<article class="recipe"><h3>Vegetable soup</h3><ul><li>Mixed non-starchy vegetables 300 g</li><li>Water 350–450 ml</li><li>Oil 0–5 g</li><li>Herbs/spices</li></ul><p>Cook and blend partly if desired. No stock cubes by default because sodium varies widely.</p></article>
</div></section>
<div class="grid"><section class="card"><div class="ey">MOVEMENT + RECOVERY</div><h2>Default weekly movement</h2><div class="life"><article><b>Aerobic</b><p>30 min moderate walking/cycling × 5 days/week. Start lower if deconditioned and build toward 150 min/week.</p></article><article><b>Strength</b><p>2 days/week: sit-to-stand, wall/bench push, supported row, heel raise or equivalent major-muscle exercises. Start 1–2 sets of 8–12 comfortable reps.</p></article><article><b>Motor rehab</b><p>If a deficit exists, practise that exact movement daily and measure the same task again.</p></article><article><b>Sitting</b><p>Break prolonged sitting regularly with brief safe movement.</p></article></div></section>
<section class="card"><div class="ey">BREATHING + SLEEP</div><h2>Default autonomic / recovery block</h2><div class="life"><article><b>Breathing</b><p>5–10 min of slow comfortable diaphragmatic breathing once or twice daily. No breath-holding or straining.</p></article><article><b>Sleep</b><p>Keep a consistent sleep and wake time; measure actual sleep duration and daytime fatigue before adding more complex sleep interventions.</p></article><article><b>Alcohol</b><p>Default stroke/TG plan uses no routine alcohol. Personalisation can change this only when clinically appropriate.</p></article><article><b>Smoking</b><p>If present, smoking cessation becomes a priority treatment module.</p></article></div></section></div>
<section class="card"><div class="ey">MEASURE</div><h2>What tells us whether the plan worked</h2><table class="targets"><thead><tr><th>Output</th><th>Baseline</th><th>Repeat</th><th>Decision</th></tr></thead><tbody><tr><td>BP / pulse</td><td>7-day home average</td><td>Repeat same protocol after controlled change</td><td>KEEP / MODIFY / INVESTIGATE</td></tr><tr><td>Triglycerides</td><td>Fasting TG</td><td>Repeat under same pre-test conditions after defined intervention interval</td><td>Compare ΔTG with verified input change</td></tr><tr><td>LDL / non-HDL / apoB</td><td>Same lipid method</td><td>Repeat same outputs</td><td>Judge endpoint response, not theory</td></tr><tr><td>Function</td><td>Grip, 10-m walk, sit-to-stand, dexterity as relevant</td><td>Same test after rehab block</td><td>Progress / change / investigate</td></tr></tbody></table></section>
<section class="card"><div class="ey">PERSONALISATION GATES</div><h2>How the generic plan becomes the real patient plan</h2><div class="life"><article><b>Kidney / potassium</b><p>Abnormal potassium or kidney function overrides fruit, vegetable, salt-substitute and supplement choices.</p></article><article><b>Liver</b><p>Raised liver enzymes change alcohol, supplement and medicine-safety decisions and trigger monitoring.</p></article><article><b>Bleeding / antiplatelets</b><p>Low platelets, bleeding symptoms or antiplatelet therapy block casual addition of products promoted as “natural blood thinners.”</p></article><article><b>Swallowing</b><p>Dysphagia changes texture, fluid and food form before any recipe is assigned.</p></article><article><b>Body size / energy</b><p>Food quantities are scaled after height, weight, body composition, activity and goal are known.</p></article><article><b>Diabetes / glucose</b><p>Glucose/HbA1c changes carbohydrate distribution and monitoring.</p></article><article><b>Medicines</b><p>Exercise intensity, food/supplement interactions and monitoring are adjusted around actual prescriptions.</p></article><article><b>Preferences</b><p>Vegetarian, Jain, vegan, non-veg, allergies, intolerances and culture select equivalent foods without changing the required output.</p></article></div><div class="gate"><b>Hospital rule</b>The generic plan is the starting prescription. The named patient's labs, medicines, body measurements and response then change the foods, grams, exercise dose, therapy modules and monitoring. Unknown data remain visible instead of being guessed.</div></section>
<p class="small">Evidence anchors used for this seed default: AHA secondary stroke prevention guidance supports low-salt / Mediterranean-style dietary patterns and physical activity; ACC hypertriglyceridemia guidance uses 150 min/week moderate activity and control of high-glycemic foods/alcohol; randomized-trial meta-analyses support about 10.2 g/day psyllium for LDL lowering and about 2 g/day plant sterols/stanols for LDL lowering. This page is a disease-default template, not an instruction to stop or replace prescribed stroke medicines.</p>
</main></body></html>