<?php
declare(strict_types=1);
require __DIR__ . '/_guard.php';
require __DIR__ . '/lib.php';
$pdo=db();
$case=require_case();
$subject=(string)$case['subject_key'];

function norm_med(string $s): string { return strtolower(preg_replace('/[^a-z0-9]+/i',' ',trim($s)) ?? ''); }
function parse_range(?string $s): ?array {
    if(!$s) return null;
    $s=str_replace([',','–','—'],['','-','-'],$s);
    if(preg_match('/(-?\d+(?:\.\d+)?)\s*-\s*(-?\d+(?:\.\d+)?)/',$s,$m)) return [(float)$m[1],(float)$m[2]];
    if(preg_match('/(?:<|less than)\s*(-?\d+(?:\.\d+)?)/i',$s,$m)) return [null,(float)$m[1]];
    if(preg_match('/(?:>|greater than)\s*(-?\d+(?:\.\d+)?)/i',$s,$m)) return [(float)$m[1],null];
    return null;
}
function optimistic_result(array $r): array {
    $value=$r['reported_numeric_value']; $range=parse_range($r['reported_reference_range_text']??null);
    $identity=(string)($r['identity_status']??'UNLINKED');
    $base=['name'=>$r['reported_test_name'],'value'=>$r['reported_value_text'],'unit'=>$r['reported_unit'],'date'=>$r['observed_on'],'range'=>$r['reported_reference_range_text'],'loinc'=>$r['exact_loinc_num'],'identity_status'=>$identity];
    if($value===null || !$range) return $base+['status'=>'unknown','headline'=>'Recorded — needs interpretation','meaning'=>'The result is preserved exactly as reported. A reliable numeric reference-range comparison is not available yet.'];
    [$lo,$hi]=$range; $v=(float)$value; $in=($lo===null||$v>=$lo)&&($hi===null||$v<=$hi);
    if($in) return $base+['status'=>'reassuring','headline'=>'Within the printed reference range','meaning'=>'This part of the report is reassuring against the laboratory range printed on the source report.'];
    $direction=$lo!==null&&$v<$lo?'below':'above';
    return $base+['status'=>'attention','headline'=>ucfirst($direction).' the printed reference range','meaning'=>'This deserves attention, but one abnormal value is not a diagnosis. The next step is to connect it to the patient context, trend, medicines and exact test identity.'];
}
function medicine_knowledge(string $name,string $strength=''): array {
    $n=norm_med($name.' '.$strength);
    $basePh='pH is not used as a generic “body pH” lever. It enters only if a measured compartment-specific pH abnormality has a verified causal path to the required output.';
    $rules=[
      ['match'=>['clopidogrel','clopilet'],'target'=>'P2Y12 ADP receptor on platelets','target_job'=>'Amplifies ADP-driven platelet activation and aggregation during normal hemostasis.','location'=>'Platelets / blood / hemostatic system','effect'=>'Platelet aggregation ↓','mechanism'=>'P2Y12 inhibition → ADP signalling ↓','benefit'=>'Lowers the platelet contribution to arterial thrombus formation where platelet activation contributes.','collateral'=>'The same platelet inhibition also reduces normal hemostasis, so bruising and bleeding can increase; rare TTP is reported.','secondary_job'=>'Platelets are also required to stop normal bleeding after vessel injury.','ilmb'=>'Reduce pathological thrombosis through endothelial state, metabolic load, fibrinolysis and vascular state without deliberately disabling P2Y12.','route'=>'Vascular state → endothelial function → metabolic/thrombotic load → fibrinolytic balance → recurrence surveillance.','action'=>'Keep prescribed antiplatelet therapy unchanged. Establish bleeding/CBC baseline, vascular risk state, food chemistry and movement baseline before changing any ILMB input.','duration'=>'Baseline first; then one controlled ILMB input at a time with a defined review interval.','decision'=>'ILMB remains supportive unless equivalent antithrombotic protection is directly demonstrated.','equivalence'=>'Supportive only — not a P2Y12 substitute.','measure'=>'Bleeding history, CBC/platelets and, when clinically used, platelet-function testing.','chebi'=>'Use exact governed chemical identities for any vascular/metabolic input; no food chemical is treated as a P2Y12 substitute.','loinc'=>'CBC/platelet and risk-factor measurements use exact verified LOINC identities when available.','therapies'=>'Food chemistry, movement, sleep/autonomic work and rehabilitation may reduce non-platelet contributors only.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['aspirin','ecosprin'],'target'=>'Platelet COX-1 → thromboxane A₂ pathway','target_job'=>'Supports thromboxane generation used for platelet activation and hemostatic clot formation.','location'=>'Platelets; gastrointestinal prostaglandin biology is a relevant collateral branch','effect'=>'TXA₂-mediated platelet aggregation ↓','mechanism'=>'COX-1 inhibition → thromboxane ↓','benefit'=>'Reduces a platelet route that can participate in arterial thrombosis.','collateral'=>'Platelet hemostasis falls; gastrointestinal irritation and bleeding can occur.','secondary_job'=>'COX-derived prostaglandin biology also contributes to normal gastrointestinal mucosal protection.','ilmb'=>'Reduce net thrombosis through alternate vascular, endothelial and fibrinolytic routes while avoiding unnecessary gastrointestinal and bleeding burden.','route'=>'Endothelium + vascular inflammation + metabolic burden + fibrinolytic balance → net thrombosis state.','action'=>'Do not replace aspirin with food/exercise. Measure bleeding/GI burden, CBC/platelets and modifiable vascular-state inputs.','duration'=>'Baseline first; controlled ILMB changes are assessed against repeat vascular/metabolic outputs.','decision'=>'Direct COX-1/TXA₂ equivalence is not claimed; ILMB is adjunctive unless equivalent protection is proven.','equivalence'=>'Supportive only — not a COX-1/TXA₂ substitute.','measure'=>'Bleeding history, CBC/platelets and clinical recurrence context.','chebi'=>'Arachidonic acid ChEBI 15843 anchors the eicosanoid chemistry branch; downstream identities must use governed mappings.','loinc'=>'CBC/platelet and relevant vascular-risk measurements use exact LOINC identities.','therapies'=>'Food chemistry, movement, sleep/autonomic work and rehabilitation may converge on total vascular risk, not on aspirin’s platelet mechanism.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['amlodipine'],'target'=>'L-type calcium channels in arterial vascular smooth muscle','target_job'=>'Calcium entry supports smooth-muscle contraction and vascular tone.','location'=>'Arterial vascular smooth muscle / systemic circulation','effect'=>'Blood pressure / vascular resistance ↓','mechanism'=>'L-type Ca²⁺ blockade → arterial relaxation','benefit'=>'Lower systemic vascular resistance reduces blood-pressure load and cardiac afterload.','collateral'=>'Vasodilation can cause edema, dizziness and hypotension.','secondary_job'=>'Vascular tone is also needed for pressure adaptation and fluid distribution; excessive arteriolar dilation can contribute to peripheral edema.','ilmb'=>'Lower vascular resistance and blood pressure through endothelial, sodium/fluid, sleep, autonomic and conditioning routes without pharmacologic calcium-channel blockade.','route'=>'Measured BP → sodium/fluid chemistry + sleep/autonomic state + conditioning → vascular resistance → repeat BP.','action'=>'Build a 7-day seated BP/pulse baseline, record edema/dizziness, then change one verified input at a time.','duration'=>'7-day baseline; review each controlled change against repeat home BP trend.','decision'=>'Keep/modify the ILMB input only if BP trend improves without symptomatic hypotension or new burden.','equivalence'=>'Functional target comparison; mechanism is different.','measure'=>'Home and clinic SBP/DBP, edema and dizziness.','chebi'=>'Nitric oxide ChEBI 16480 may anchor an endothelial-relaxation route only where the input→NO→vascular-output chain is verified.','loinc'=>'BP/pulse plus any laboratory contributors must retain exact measurement identity; do not mix unlike methods.','therapies'=>'Movement/conditioning, sleep, breathing/yoga and other autonomic approaches converge only if the measured BP output changes reproducibly.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['atenolol'],'target'=>'β1-adrenergic signalling, primarily cardiac','target_job'=>'Sympathetic β1 signalling increases heart rate and contractile drive during demand.','location'=>'Heart; renal β1 signalling is a secondary physiologic branch','effect'=>'Heart rate and cardiac workload ↓','mechanism'=>'β1 blockade','benefit'=>'Reduces sympathetic cardiac drive where lower HR/workload is therapeutically useful.','collateral'=>'Can cause bradycardia, hypotension, fatigue, tiredness and dizziness and can suppress exercise heart-rate response.','secondary_job'=>'β1 signalling normally helps the cardiovascular system respond to exertion and physiologic demand.','ilmb'=>'Lower resting cardiac demand through conditioning, sleep and autonomic regulation without β1 blockade.','route'=>'Resting HR/BP + exertion response → sleep/autonomic state + graded conditioning → cardiac demand → repeat HR/BP/function.','action'=>'Record resting HR/BP and perceived exertion; use workload/RPE rather than generic age-based target HR while taking atenolol.','duration'=>'Baseline over 7 days; graded conditioning is progressed only from measured tolerance.','decision'=>'Progress only if function improves without symptomatic bradycardia, hypotension, chest symptoms or excess fatigue.','equivalence'=>'Functional target comparison; not β1 blockade.','measure'=>'Resting HR/BP, symptoms and functional capacity.','chebi'=>'No dietary chemical is treated as a β1 substitute; chemistry may support upstream autonomic/metabolic state only where mapped.','loinc'=>'Resting pulse/BP and functional outputs must use the same protocol before and after intervention.','therapies'=>'Conditioning, breathing/yoga, sleep restoration and stress work may converge on autonomic output; EMDR enters only if a measured trauma/stress driver exists.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['atorvastatin','lipvas'],'target'=>'Hepatic HMG-CoA reductase pathway','target_job'=>'Supports endogenous cholesterol synthesis used in membranes and other cholesterol-dependent biology.','location'=>'Liver / cholesterol synthesis and lipoprotein clearance system','effect'=>'LDL / apoB ↓','mechanism'=>'HMG-CoA reductase inhibition → LDL clearance ↑','benefit'=>'Lowers circulating atherogenic particle burden.','collateral'=>'Muscle injury/myopathy and liver-enzyme abnormalities can occur; rare rhabdomyolysis is documented.','secondary_job'=>'The targeted pathway is part of normal hepatic cholesterol synthesis; systemic exposure means muscle and liver safety are monitored.','ilmb'=>'Lower LDL/apoB through intestinal, food-chemistry, hepatic-substrate and metabolic routes without directly inhibiting HMG-CoA reductase.','route'=>'Weighed food chemistry → intestinal/hepatic substrate load → LDL/non-HDL/apoB → repeat lipid panel.','action'=>'Capture 3 normal weighed food days, map grams to nutrient/chemical composition, then choose one measurable lipid-relevant input to modify.','duration'=>'Three-day baseline; hold the selected input steady until the planned repeat lipid measurement.','decision'=>'Keep/modify based on change in LDL/non-HDL/apoB and treatment burden, not assumption.','equivalence'=>'Same output target; different biological route.','measure'=>'LDL-C, non-HDL-C, apoB if available, liver enzymes and muscle symptoms.','chebi'=>'Food and metabolite inputs must use exact governed chemical identities before entering the lipid equation.','loinc'=>'ALT LOINC 1742-6 is one safety output; lipid measurements must retain exact identities/method context.','therapies'=>'Food chemistry and movement/body-composition modules converge on lipid output; unrelated modalities are excluded unless a measured path exists.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['fenofibrate','finobrate'],'target'=>'PPARα-regulated fatty-acid and lipoprotein metabolism','target_job'=>'Coordinates genes involved in fatty-acid oxidation and triglyceride-rich lipoprotein handling.','location'=>'Liver and systemic lipid-metabolism network; muscle/kidney/gallbladder are relevant safety branches','effect'=>'Triglyceride-rich particles ↓','mechanism'=>'PPARα activation → triglyceride clearance ↑','benefit'=>'Lowers the measured triglyceride-rich lipoprotein burden.','collateral'=>'Liver injury/enzyme rise, muscle injury, reversible creatinine rise and gallstones can occur; muscle risk is higher with a statin.','secondary_job'=>'Liver, kidney, muscle and gallbladder functions carry treatment-safety consequences and must be trended separately from benefit.','ilmb'=>'Reduce triglyceride production and increase fatty-acid/triglyceride utilisation through food chemistry, hepatic substrate control, gut-metabolic routes and muscle activity without pharmacologic PPARα activation.','route'=>'3 weighed food days → IFCT/USDA composition → verified chemical input → ChEBI identity → movement dose → fasting TG → repeat.','action'=>'Quantify actual food/drink grams and measured movement; change one TG-relevant input rather than giving a generic diet.','duration'=>'Three-day input baseline, then hold one defined change steady until fasting TG is rechecked.','decision'=>'Compute personal response from ΔTG / Δverified input and keep, modify or investigate from N=1 response.','equivalence'=>'Same output target; different biological route.','measure'=>'Fasting triglycerides, ALT/AST, creatinine/eGFR and muscle symptoms.','chebi'=>'Every dietary substrate/metabolite must map to an exact chemical identity before dose-response arithmetic.','loinc'=>'Triglycerides LOINC 2571-8; ALT 1742-6; creatinine 2160-0; eGFR and movement workload add safety/output context.','therapies'=>'Food chemistry and muscle activity are primary convergence modules; yoga or other modalities enter only if a quantified path reaches TG output.','ph_gate'=>$basePh,'confidence'=>'mapped'],
      ['match'=>['cod liver oil','seacap'],'target'=>'Nutrient-dependent biochemical pathways determined by exact EPA/DHA/vitamin A/vitamin D content','target_job'=>'Each nutrient has its own substrate/cofactor role; the product name alone does not define the biochemical dose.','location'=>'Multiple tissues depending on constituent; exact formulation controls pathway relevance','effect'=>'Nutrient exposure','mechanism'=>'Depends on actual EPA, DHA, vitamin A and vitamin D content','benefit'=>'Useful only when the constituent dose matches a measured requirement.','collateral'=>'Dose-dependent nutrient excess and interaction burden are possible; bleeding relevance depends on actual EPA/DHA exposure.','secondary_job'=>'Fatty acids and fat-soluble vitamins participate in multiple normal pathways, so excess can affect more than the intended target.','ilmb'=>'Read exact label chemistry → quantify chemical intake → compare with measured requirement → track response.','route'=>'Product label → mg/µg of each constituent → chemical identity → existing food/supplement intake → biomarker/need → decision.','action'=>'Do not treat “300 mg cod liver oil” as a known EPA/DHA dose. Record the exact label composition first.','duration'=>'Immediate identity check; nutrient dosing follows only after total intake and measured need are known.','decision'=>'Keep/modify only from verified constituent dose plus relevant biomarker/clinical need.','equivalence'=>'Requirement-based nutrient calculation, not a medicine substitute.','measure'=>'Exact product chemistry plus relevant nutrient biomarkers.','chebi'=>'Each constituent requires exact chemical/form identity before dose arithmetic.','loinc'=>'Relevant nutrient biomarkers use exact LOINC identity where available.','therapies'=>'No therapy substitutes for a demonstrated missing chemical requirement.','ph_gate'=>$basePh,'confidence'=>'conditional'],
      ['match'=>['neurobion'],'target'=>'Multiple B-vitamin cofactor-dependent pathways','target_job'=>'B vitamins act as cofactors in many biochemical reactions; exact formulation determines which pathways are affected.','location'=>'Multiple tissues and metabolic pathways','effect'=>'B-vitamin cofactor support','mechanism'=>'Provides multiple B vitamins used in cofactor-dependent pathways','benefit'=>'Useful only when an individual nutrient requirement is present and corrected.','collateral'=>'Unnecessary or excessive dosing can also create effects; formulation matters.','secondary_job'=>'Because each B vitamin participates in different normal pathways, brand-level dosing cannot be treated as one biochemical action.','ilmb'=>'Requirement-first food/supplement calculation for each nutrient rather than treating a multivitamin as a single intervention.','route'=>'Exact formulation → each B-vitamin dose → food intake → deficiency/need marker → total exposure → response.','action'=>'Verify formulation and quantify each nutrient separately before deciding whether food or supplementation is required.','duration'=>'Identity and baseline first; follow-up timing depends on the nutrient and measured deficiency.','decision'=>'Keep/modify individual nutrients from measured need and response rather than brand-level assumptions.','equivalence'=>'Nutrient requirement pathway.','measure'=>'B12 and need-specific markers where relevant.','chebi'=>'Each vitamin/form requires exact chemical identity before arithmetic.','loinc'=>'Need-specific nutrient biomarkers use exact verified LOINC identities where available.','therapies'=>'No therapy substitutes for a proven biochemical deficit; symptom/function therapies remain separate.','ph_gate'=>$basePh,'confidence'=>'conditional']
    ];
    foreach($rules as $r){foreach($r['match'] as $m){if(str_contains($n,$m)){unset($r['match']);return $r;}}}
    return ['target'=>'Unverified','target_job'=>'Unknown until the exact ingredient/formulation is verified.','location'=>'Unknown','effect'=>'Not mapped yet','mechanism'=>'The medicine name is recorded, but a governed mechanism mapping has not yet been attached.','benefit'=>'Blocked until indication and target are verified.','collateral'=>'Do not infer side effects from the name alone until the exact ingredient/formulation is verified.','secondary_job'=>'Unknown','ilmb'=>'No ILMB comparison is generated until the medicine identity, treatment target and required physiological output are verified.','route'=>'Identity → indication → physiological output must be resolved before an ILMB path is generated.','action'=>'Verify ingredient, strength, indication and monitoring plan.','duration'=>'Not set until identity and target are verified.','decision'=>'Blocked: no treatment-path claim from an unverified medicine identity.','equivalence'=>'Not established.','measure'=>'Verify ingredient, strength, indication and monitoring plan.','chebi'=>'Blocked until chemical identity is verified.','loinc'=>'Blocked until required output measurement is defined.','therapies'=>'Blocked until the required physiological output is defined.','ph_gate'=>$basePh,'confidence'=>'needs_mapping'];
}

if($_SERVER['REQUEST_METHOD']!=='GET') json_out(['ok'=>false,'error'=>'Unsupported action.'],405);
$results=[];
try{
  $q=$pdo->prepare("SELECT result_id,source_document_id,observed_on,reported_test_name,reported_value_text,reported_numeric_value,reported_unit,reported_specimen_text,laboratory_name,reported_reference_range_text,exact_loinc_num,identity_status,created_at FROM v_ilb_subject_test_result_visible WHERE subject_key=? ORDER BY observed_on DESC,result_id DESC");
  $q->execute([$subject]); foreach($q->fetchAll() as $r)$results[]=optimistic_result($r);
}catch(Throwable $e){error_log('hospital review results: '.$e->getMessage());}
$meds=[];
$q=$pdo->prepare("SELECT medicine_report_id,reported_name,strength_text,dose_text,frequency_text,usual_time_text,reason_text,verification_status FROM ilb_subject_medicine_report WHERE subject_key=? AND status='active' ORDER BY medicine_report_id");
$q->execute([$subject]);
foreach($q->fetchAll() as $m){$k=medicine_knowledge((string)$m['reported_name'],(string)($m['strength_text']??''));$meds[]=array_merge($m,$k);}
$docs=[];
$q=$pdo->prepare("SELECT document_id,document_type,document_date,original_filename,extraction_status,human_review_status FROM ilb_subject_document WHERE subject_key=? ORDER BY COALESCE(document_date,DATE(created_at)) DESC,document_id DESC");
$q->execute([$subject]);
foreach($q->fetchAll() as $d){$status=(string)($d['human_review_status']??'not_reviewed');$d['patient_message']=$status==='reviewed'?'Reviewed and linked to your case.':'Safely stored. Structured reading/review is still pending.';$docs[]=$d;}
$count=['reassuring'=>0,'attention'=>0,'unknown'=>0];foreach($results as $r)$count[$r['status']]++;
$paths=[];foreach($meds as $m){$paths[]=['medicine'=>$m['reported_name'],'goal'=>$m['effect'],'equivalence'=>$m['equivalence'],'route'=>$m['route'],'action'=>$m['action'],'duration'=>$m['duration'],'measure'=>$m['measure'],'decision'=>$m['decision'],'target'=>$m['target'],'target_job'=>$m['target_job'],'location'=>$m['location'],'benefit'=>$m['benefit'],'secondary_job'=>$m['secondary_job'],'chebi'=>$m['chebi'],'loinc'=>$m['loinc'],'therapies'=>$m['therapies'],'ph_gate'=>$m['ph_gate'],'confidence'=>$m['confidence']];}
json_out(['ok'=>true,'case'=>['label'=>$case['frontend_label'],'age'=>$case['allowed_age_display'],'sex'=>$case['allowed_sex_display']],
  'summary'=>['reassuring'=>$count['reassuring'],'attention'=>$count['attention'],'unknown'=>$count['unknown'],'message'=>'Start with what is reassuring, then what needs attention, then what remains unknown. Nothing abnormal is hidden and nothing unverified is promoted to fact.'],
  'results'=>$results,'medicines'=>$meds,'ilmb_paths'=>$paths,'documents'=>$docs,
  'identity_layer'=>['loinc'=>'Exact test identity when verified','chebi'=>'Chemical identity for governed nutrient/biochemical mappings','reactome'=>'Pathway connection where endpoint identity and evidence are resolved','ph'=>'Compartment-specific only: blood, urine, gastric and intracellular pH are not interchangeable'],
  'loop'=>'MEDICINE → TARGET → TARGET JOB → DESIRED OUTPUT → COLLATERAL BRANCH → ILMB CONVERGENCE → SAME OUTPUT MEASUREMENT → KEEP / MODIFY / INVESTIGATE / ESCALATE',
  'boundary'=>'This review explains records and treatment logic. It does not instruct a patient to stop or change a prescription.']);
