<?php declare(strict_types=1); require __DIR__.'/_guard.php'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Psoriasis Body Intake · ILoveMyBody</title><style>
:root{--ink:#17332d;--muted:#60736e;--paper:#fbfaf5;--card:#fff;--jade:#087864;--gold:#c58b35;--line:#dce6e1;--warn:#fff4da}*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#eff8f4,#fbf6ea);font:15px/1.45 system-ui,sans-serif;color:var(--ink)}main{max-width:1180px;margin:auto;padding:22px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:18px}h1{font:700 clamp(28px,4vw,48px)/1.05 Georgia,serif;margin:0}.sub{color:var(--muted);max-width:720px}.bar,.card{background:var(--card);border:1px solid var(--line);border-radius:18px;box-shadow:0 10px 32px #17332d12}.bar{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;padding:14px;margin-bottom:18px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.card{padding:18px;margin-bottom:14px}h2{font:700 21px Georgia,serif;margin:0 0 12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}label{display:grid;gap:5px;font-weight:650}small,.hint{font-weight:400;color:var(--muted)}input,select,textarea,button{font:inherit;border-radius:10px;border:1px solid #bccdc6;padding:10px;background:white;color:var(--ink)}textarea{min-height:78px;resize:vertical}button{border:0;background:var(--jade);color:white;font-weight:750;cursor:pointer;padding:11px 18px}.secondary{background:#e9f2ee;color:var(--ink)}.gate{padding:10px 0;border-bottom:1px solid var(--line)}.gate:last-child{border:0}.blocked{color:#995e00;font-weight:800}.notice{background:var(--warn);border-radius:12px;padding:12px;margin-bottom:12px}.actions{position:sticky;bottom:10px;display:flex;justify-content:flex-end;gap:10px;padding:10px;background:#ffffffdd;backdrop-filter:blur(8px);border-radius:14px}.status{min-height:24px;font-weight:700}@media(max-width:800px){.layout{grid-template-columns:1fr}.bar,.grid{grid-template-columns:1fr}.hero{display:block}main{padding:14px}.actions{justify-content:stretch}.actions button{flex:1}}
</style></head><body><main><div class="hero"><div><h1>Psoriasis body intake</h1><p class="sub">One measured timeline for skin, symptoms, quality of life, laboratory data, medicine exposure, side effects and daily living. Saved information remains unverified until reviewed.</p></div><a href="./" class="hint">Back to hospital</a></div>
<div class="bar"><label>Episode ID<input id="episode" placeholder="PSO-2026-001"></label><label>Observation time<input id="observed" type="datetime-local"></label><button id="load" class="secondary">Load episode</button></div>
<div class="layout"><section><div class="notice">This form records observations. It does not calculate equivalence or recommend stopping, starting or replacing treatment.</div><form id="intake"></form><div class="card"><h2>Medicine exposure</h2><div class="grid"><label>Name as recorded<input id="medName"></label><label>Dose<input id="medDose" type="number" step="any"></label><label>Dose unit<input id="medUnit"></label><label>Route<input id="medRoute"></label><label>Start<input id="medStart" type="datetime-local"></label><label>Schedule<input id="medSchedule"></label></div><p><label><span><input id="prescribed" type="checkbox"> Prescribed/confirmed by treating clinician</span></label></p><button id="saveMed" type="button">Save medicine exposure</button></div>
<div class="card"><h2>Side effect or safety event</h2><div class="grid"><label>What happened<textarea id="aeLabel"></textarea></label><label>Severity<select id="aeSeverity"><option>UNKNOWN</option><option>MILD</option><option>MODERATE</option><option>SEVERE</option><option>LIFE_THREATENING</option></select></label><label>Onset<input id="aeOnset" type="datetime-local"></label><label><span><input id="aeSerious" type="checkbox"> Serious event</span></label><label>Action taken<textarea id="aeAction"></textarea></label><label>Outcome<textarea id="aeOutcome"></textarea></label></div><button id="saveAe" type="button">Save safety event</button></div>
<div class="actions"><div id="status" class="status"></div><button id="save" type="button">Save observations</button></div></section><aside><div class="card"><h2>Calculation gates</h2><div id="gates">Loading…</div></div><div class="card"><h2>Why values remain separate</h2><p class="hint">A symptom score is not a laboratory value. A lifestyle choice is not a drug dose. A reported side effect is not automatically caused by a medicine. Synchronicity is created through time, units, body site, provenance and reviewed equations.</p></div></aside></div></main><script>
const api='psoriasis-intake-api.php'; const form=document.querySelector('#intake'),statusEl=document.querySelector('#status'); let defs=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function episode(){const v=document.querySelector('#episode').value.trim();if(!/^PSO-[A-Za-z0-9_-]{1,80}$/.test(v))throw Error('Enter an episode ID beginning PSO-.');return v}function say(s,bad=false){statusEl.textContent=s;statusEl.style.color=bad?'#a02a2a':'#087864'}
async function call(action,body){const r=await fetch(api+'?action='+action,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):null});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Request failed');return j}
function render(){const groups=defs.reduce((a,d)=>{(a[d.category_code]??=[]).push(d);return a},{});form.innerHTML=Object.entries(groups).map(([cat,rows])=>`<div class="card"><h2>${esc(cat.replaceAll('_',' '))}</h2><div class="grid">${rows.map(d=>{const type=['NUMBER','INTEGER'].includes(d.value_domain)?'number':'text';return `<label>${esc(d.label)} ${d.release_required==1?'<small>required for release</small>':''}<input data-code="${esc(d.input_code)}" data-site="${d.body_site_required}" type="${type}" step="any"><small>${esc(d.canonical_unit_code||d.time_basis||'')}</small>${d.body_site_required==1?`<input data-body-site="${esc(d.input_code)}" placeholder="Body site">`:''}</label>`}).join('')}</div></div>`).join('')}
async function boot(){const j=await call('bootstrap');defs=j.definitions;render();document.querySelector('#gates').innerHTML=j.gates.map(g=>`<div class="gate"><span class="blocked">${esc(g.gate_status)}</span> · ${esc(g.gate_code)}<div class="hint">${esc(g.reason_text)}</div></div>`).join('');const n=new Date();n.setMinutes(n.getMinutes()-n.getTimezoneOffset());document.querySelector('#observed').value=n.toISOString().slice(0,16)}
document.querySelector('#save').onclick=async()=>{try{const observations=[...document.querySelectorAll('[data-code]')].filter(x=>x.value!=='').map(x=>({input_code:x.dataset.code,value:x.value,body_site:document.querySelector(`[data-body-site="${x.dataset.code}"]`)?.value||''}));const j=await call('save',{episode_key:episode(),observed_at:document.querySelector('#observed').value,observations});say(`Saved ${j.saved} observations for review.`)}catch(e){say(e.message,true)}};
document.querySelector('#saveMed').onclick=async()=>{try{await call('save_medicine',{episode_key:episode(),medicine_name:medName.value,dose_value:medDose.value,dose_unit:medUnit.value,route_code:medRoute.value,start_at:medStart.value,schedule_text:medSchedule.value,prescribed_flag:prescribed.checked});say('Medicine exposure saved as pending verification.')}catch(e){say(e.message,true)}};
document.querySelector('#saveAe').onclick=async()=>{try{await call('save_adverse_event',{episode_key:episode(),event_label:aeLabel.value,severity:aeSeverity.value,onset_at:aeOnset.value,seriousness_flag:aeSerious.checked,action_taken:aeAction.value,outcome_text:aeOutcome.value});say('Safety event saved for clinician review.')}catch(e){say(e.message,true)}};
document.querySelector('#load').onclick=async()=>{try{const r=await fetch(api+'?action=episode&episode_key='+encodeURIComponent(episode()));const j=await r.json();if(!j.ok)throw Error(j.error);for(const o of j.observations){const x=document.querySelector(`[data-code="${o.input_code}"]`);if(x&&!x.value)x.value=o.value_number??o.value_text??'';const s=document.querySelector(`[data-body-site="${o.input_code}"]`);if(s&&!s.value)s.value=o.body_site??''}say(`Loaded ${j.observations.length} observations.`)}catch(e){say(e.message,true)}};boot().catch(e=>say(e.message,true));
</script></body></html>
