CREATE TABLE IF NOT EXISTS ilmb_entity_crosswalk (
  mapping_id CHAR(64) PRIMARY KEY,
  source_system VARCHAR(64) NOT NULL,
  source_entity_type VARCHAR(32) NOT NULL,
  source_id VARCHAR(255) NOT NULL,
  predicate VARCHAR(64) NOT NULL,
  target_system VARCHAR(64) NOT NULL,
  target_entity_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(255) NOT NULL,
  match_type ENUM('EXACT','BROADER','NARROWER','RELATED','CANDIDATE') NOT NULL,
  status ENUM('DRAFT','APPROVED','REJECTED','RETIRED') NOT NULL,
  evidence_source VARCHAR(255) NOT NULL,
  evidence_version VARCHAR(128) NOT NULL,
  evidence_locator VARCHAR(512) NULL,
  confidence DECIMAL(6,5) NULL,
  computation_eligible BOOLEAN NOT NULL DEFAULT FALSE,
  source_batch_id CHAR(36) NOT NULL,
  row_hash CHAR(64) NOT NULL,
  effective_at DATETIME(6) NOT NULL,
  retired_at DATETIME(6) NULL,
  UNIQUE KEY uq_crosswalk_natural (source_system, source_id, predicate, target_system, target_id),
  INDEX ix_crosswalk_source (source_system, source_entity_type, source_id),
  INDEX ix_crosswalk_target (target_system, target_entity_type, target_id),
  INDEX ix_crosswalk_compute (computation_eligible, status, match_type),
  INDEX ix_crosswalk_batch (source_batch_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ilmb_entity_crosswalk_history (
  history_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  mapping_id CHAR(64) NOT NULL,
  source_system VARCHAR(64) NOT NULL,
  source_entity_type VARCHAR(32) NOT NULL,
  source_id VARCHAR(255) NOT NULL,
  predicate VARCHAR(64) NOT NULL,
  target_system VARCHAR(64) NOT NULL,
  target_entity_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(255) NOT NULL,
  match_type VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  evidence_source VARCHAR(255) NOT NULL,
  evidence_version VARCHAR(128) NOT NULL,
  evidence_locator VARCHAR(512) NULL,
  confidence DECIMAL(6,5) NULL,
  computation_eligible BOOLEAN NOT NULL,
  source_batch_id CHAR(36) NOT NULL,
  row_hash CHAR(64) NOT NULL,
  effective_at DATETIME(6) NOT NULL,
  retired_at DATETIME(6) NULL,
  replaced_at DATETIME(6) NOT NULL,
  replaced_by_batch_id CHAR(36) NOT NULL,
  INDEX ix_crosswalk_history_mapping (mapping_id),
  INDEX ix_crosswalk_history_batch (source_batch_id)
) ENGINE=InnoDB;
