<?php
declare(strict_types=1);ini_set('display_errors','stderr');error_reporting(E_ALL);const EXPECTED_DATABASE='u756742628_ilovemybody';if(PHP_SAPI!=='cli')exit(2);
$config=require($argv[1]??'');if(isset($config['database'])&&is_array($config['database']))$config=$config['database'];$database=$config['db']??($config['name']??null);if($database!==EXPECTED_DATABASE)throw new RuntimeException('Unexpected database');$sqlPath=$argv[2]??'';if(!is_file($sqlPath))throw new RuntimeException('Phase 85 SQL missing');
$pdo=new PDO('mysql:host='.$config['host'].';port='.($config['port']??3306).';dbname='.$database.';charset=utf8mb4',$config['user'],$config['pass']??$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::MYSQL_ATTR_MULTI_STATEMENTS=>true,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$s=$pdo->prepare(file_get_contents($sqlPath));$s->execute();do{if($s->columnCount())$s->fetchAll();}while($s->nextRowset());$s->closeCursor();
$outcomes=$pdo->query('SELECT agent_key,nct_id,outcome_index,outcome_class,outcome_json FROM ilb_psoriasis_aggregate_outcome ORDER BY agent_key,nct_id,outcome_index')->fetchAll();if(!$outcomes)throw new RuntimeException('No aggregate outcomes available');$rows=[];
foreach($outcomes as $o){$v=json_decode($o['outcome_json'],true,512,JSON_THROW_ON_ERROR);foreach(($v['classes']??[]) as $ci=>$class){$denoms=isset($class['denoms'])?json_encode($class['denoms'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR):null;foreach(($class['categories']??[]) as $ki=>$cat){foreach(($cat['measurements']??[]) as $mi=>$m){$json=json_encode($m,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$rows[]=[$o['agent_key'],$o['nct_id'],$o['outcome_index'],$ci,$ki,$mi,$o['outcome_class'],$class['title']??null,$cat['title']??null,$m['title']??null,isset($m['value'])?(string)$m['value']:null,isset($m['spread'])?(string)$m['spread']:null,isset($m['lowerLimit'])?(string)$m['lowerLimit']:null,isset($m['upperLimit'])?(string)$m['upperLimit']:null,$denoms,$json,hash('sha256',$json)];}}}}
if(!$rows)throw new RuntimeException('No aggregate measurement cells extracted');$pdo->beginTransaction();try{$pdo->exec('DELETE FROM ilb_psoriasis_aggregate_measurement');$i=$pdo->prepare('INSERT INTO ilb_psoriasis_aggregate_measurement(agent_key,nct_id,outcome_index,class_index,category_index,measurement_index,outcome_class,class_title,category_title,measurement_title,value_text,spread_text,lower_limit_text,upper_limit_text,denominator_json,measurement_json,measurement_sha256,computation_eligible,extracted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,UTC_TIMESTAMP())');foreach($rows as $r)$i->execute($r);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
$covered=(int)$pdo->query('SELECT COUNT(DISTINCT agent_key) FROM ilb_psoriasis_aggregate_measurement')->fetchColumn();$byClass=$pdo->query('SELECT outcome_class,COUNT(*) measurement_count,COUNT(DISTINCT nct_id) trial_count FROM ilb_psoriasis_aggregate_measurement GROUP BY outcome_class ORDER BY outcome_class')->fetchAll();$eligible=(int)$pdo->query('SELECT COUNT(*) FROM ilb_psoriasis_aggregate_measurement WHERE computation_eligible=1')->fetchColumn();if($covered!==11||$eligible!==0)throw new RuntimeException('Measurement coverage or eligibility gate failed');
echo json_encode(['database'=>$database,'phase'=>'P85_AGGREGATE_MEASUREMENTS','outcomes_scanned'=>count($outcomes),'covered_agents'=>$covered,'aggregate_measurement_cells'=>count($rows),'by_class'=>$byClass,'computation_eligible_measurements'=>$eligible,'participant_level_data_requested'=>false,'patient_tables_queried'=>false,'patient_rows_read'=>0,'patient_rows_modified'=>0,'verified'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),PHP_EOL;
