<?php
declare(strict_types=1);ini_set('display_errors','stderr');error_reporting(E_ALL);
const EXPECTED_DATABASE='u756742628_ilovemybody';if(PHP_SAPI!=='cli')exit(2);
$config=require($argv[1]??'');if(isset($config['database'])&&is_array($config['database']))$config=$config['database'];$database=$config['db']??($config['name']??null);if($database!==EXPECTED_DATABASE)throw new RuntimeException('Unexpected database');$sqlPath=$argv[2]??'';if(!is_file($sqlPath))throw new RuntimeException('Phase 84 SQL missing');
function classify(string $title,string $description):string{$v=$title.' '.$description;if(preg_match('/\bPASI\b|Psoriasis Area and Severity Index/i',$v))return 'PASI';if(preg_match('/withdraw|relaps|time to loss|loss of response|retreatment/i',$v))return 'WITHDRAWAL_RELAPSE';if(preg_match('/\bIGA\b|\bPGA\b|Investigator.?s Global Assessment|Physician.?s Global Assessment/i',$v))return 'IGA_PGA';if(preg_match('/\bDLQI\b|Dermatology Life Quality Index/i',$v))return 'DLQI';return 'OTHER';}
$pdo=new PDO('mysql:host='.$config['host'].';port='.($config['port']??3306).';dbname='.$database.';charset=utf8mb4',$config['user'],$config['pass']??$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::MYSQL_ATTR_MULTI_STATEMENTS=>true,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$s=$pdo->prepare(file_get_contents($sqlPath));$s->execute();do{if($s->columnCount())$s->fetchAll();}while($s->nextRowset());$s->closeCursor();
$trials=$pdo->query('SELECT agent_key,nct_id,results_json,source_sha256 FROM ilb_psoriasis_aggregate_trial WHERE has_results=1 AND results_json IS NOT NULL ORDER BY agent_key,nct_id')->fetchAll();if(!$trials)throw new RuntimeException('No aggregate results available');$out=[];
foreach($trials as $t){$r=json_decode($t['results_json'],true,512,JSON_THROW_ON_ERROR);$measures=$r['outcomeMeasuresModule']['outcomeMeasures']??[];foreach($measures as $idx=>$m){$json=json_encode($m,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$title=trim((string)($m['title']??''));if($title==='')continue;$description=trim((string)($m['description']??''));$out[]=[$t['agent_key'],$t['nct_id'],$idx,classify($title,$description),$m['type']??null,$title,$description?:null,$m['timeFrame']??null,$m['units']??null,$m['paramType']??null,$m['dispersionType']??null,$json,hash('sha256',$json),$t['source_sha256']];}}
if(!$out)throw new RuntimeException('No aggregate outcome measures extracted');$pdo->beginTransaction();try{$pdo->exec('DELETE FROM ilb_psoriasis_aggregate_outcome');$i=$pdo->prepare('INSERT INTO ilb_psoriasis_aggregate_outcome(agent_key,nct_id,outcome_index,outcome_class,outcome_type,title,description,time_frame,units,param_type,dispersion_type,outcome_json,outcome_sha256,source_trial_sha256,computation_eligible,extracted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,UTC_TIMESTAMP())');foreach($out as $row)$i->execute($row);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
$covered=(int)$pdo->query('SELECT COUNT(DISTINCT agent_key) FROM ilb_psoriasis_aggregate_outcome')->fetchColumn();$byClass=$pdo->query('SELECT outcome_class,COUNT(*) outcome_count,COUNT(DISTINCT nct_id) trial_count FROM ilb_psoriasis_aggregate_outcome GROUP BY outcome_class ORDER BY outcome_class')->fetchAll();$eligible=(int)$pdo->query('SELECT COUNT(*) FROM ilb_psoriasis_aggregate_outcome WHERE computation_eligible=1')->fetchColumn();if($covered!==11||$eligible!==0)throw new RuntimeException('Outcome coverage or eligibility gate failed');
echo json_encode(['database'=>$database,'phase'=>'P84_AGGREGATE_OUTCOMES','results_trial_links_scanned'=>count($trials),'covered_agents'=>$covered,'aggregate_outcomes'=>count($out),'by_class'=>$byClass,'computation_eligible_outcomes'=>$eligible,'participant_level_data_requested'=>false,'patient_tables_queried'=>false,'patient_rows_read'=>0,'patient_rows_modified'=>0,'verified'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),PHP_EOL;
