<?php
declare(strict_types=1);ini_set('display_errors','stderr');error_reporting(E_ALL);
const EXPECTED_DATABASE='u756742628_ilovemybody';if(PHP_SAPI!=='cli')exit(2);
$config=require($argv[1]??'');if(isset($config['database'])&&is_array($config['database']))$config=$config['database'];$database=$config['db']??($config['name']??null);if($database!==EXPECTED_DATABASE)throw new RuntimeException('Unexpected database');
$sqlPath=$argv[2]??'';if(!is_file($sqlPath))throw new RuntimeException('Phase 83 SQL missing');
function getJson(string $url):array{$ctx=stream_context_create(['http'=>['timeout'=>60,'header'=>"User-Agent: ILoveMyBody-Research/1.0\r\n"]]);$raw=file_get_contents($url,false,$ctx);if($raw===false)throw new RuntimeException('ClinicalTrials.gov request failed');$v=json_decode($raw,true,512,JSON_THROW_ON_ERROR);return [$v,$raw];}
function exactIntervention(array $study,string $name):bool{foreach(($study['protocolSection']['armsInterventionsModule']['interventions']??[]) as $i)if(strcasecmp(trim((string)($i['name']??'')),$name)===0)return true;return false;}
$pdo=new PDO('mysql:host='.$config['host'].';port='.($config['port']??3306).';dbname='.$database.';charset=utf8mb4',$config['user'],$config['pass']??$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::MYSQL_ATTR_MULTI_STATEMENTS=>true,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$s=$pdo->prepare(file_get_contents($sqlPath));$s->execute();do{if($s->columnCount())$s->fetchAll();}while($s->nextRowset());$s->closeCursor();
$agents=$pdo->query("SELECT agent_key,ingredient_name FROM ilb_psoriasis_pharma_agent ORDER BY agent_key")->fetchAll();if(count($agents)!==11)throw new RuntimeException('Expected 11 registered agents');$records=[];
foreach($agents as $a){$token=null;do{$url='https://clinicaltrials.gov/api/v2/studies?format=json&pageSize=100&query.cond='.rawurlencode('Psoriasis').'&query.intr='.rawurlencode($a['ingredient_name']).($token?'&pageToken='.rawurlencode($token):'');[$page,$raw]=getJson($url);foreach(($page['studies']??[]) as $study){if(!exactIntervention($study,$a['ingredient_name']))continue;$p=$study['protocolSection']??[];$id=$p['identificationModule']['nctId']??null;if(!$id)continue;$results=$study['resultsSection']??null;$canonical=json_encode($study,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$records[$a['agent_key'].'|'.$id]=['agent'=>$a['agent_key'],'id'=>$id,'title'=>$p['identificationModule']['briefTitle']??'','status'=>$p['statusModule']['overallStatus']??null,'phases'=>$p['designModule']['phases']??null,'count'=>$p['designModule']['enrollmentInfo']['count']??null,'type'=>$p['designModule']['enrollmentInfo']['type']??null,'results'=>$results,'protocol'=>$p,'url'=>'https://clinicaltrials.gov/study/'.$id,'sha'=>hash('sha256',$canonical),'updated'=>$p['statusModule']['lastUpdatePostDateStruct']['date']??null];}$token=$page['nextPageToken']??null;}while($token);}
if(!$records)throw new RuntimeException('No exact-intervention aggregate trials returned');$covered=array_values(array_unique(array_column($records,'agent')));if(count($covered)!==11)throw new RuntimeException('Aggregate trial registry does not cover all agents: '.json_encode($covered));
$pdo->beginTransaction();try{$pdo->exec('DELETE FROM ilb_psoriasis_aggregate_trial');$i=$pdo->prepare('INSERT INTO ilb_psoriasis_aggregate_trial(agent_key,nct_id,brief_title,overall_status,phases_json,enrollment_count,enrollment_type,has_results,protocol_json,results_json,source_url,source_sha256,source_updated_date,computation_eligible,retrieved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,0,UTC_TIMESTAMP())');foreach($records as $r)$i->execute([$r['agent'],$r['id'],$r['title'],$r['status'],$r['phases']===null?null:json_encode($r['phases']),$r['count'],$r['type'],$r['results']===null?0:1,json_encode($r['protocol'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$r['results']===null?null:json_encode($r['results'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$r['url'],$r['sha'],$r['updated']]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
$summary=$pdo->query('SELECT agent_key,COUNT(*) trial_count,SUM(has_results) results_count FROM ilb_psoriasis_aggregate_trial GROUP BY agent_key ORDER BY agent_key')->fetchAll();echo json_encode(['database'=>$database,'phase'=>'P83_AGGREGATE_TRIALS','covered_agents'=>count($covered),'aggregate_trial_links'=>count($records),'by_agent'=>$summary,'computation_eligible_records'=>0,'participant_level_data_requested'=>false,'patient_tables_queried'=>false,'patient_rows_read'=>0,'patient_rows_modified'=>0,'verified'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),PHP_EOL;
